# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing
from enum import Enum, auto

class AuxiliaryTrafficArea:
    id: builtins.str
    bounded_by: typing.Optional[Envelope]
    city_object_class: CityObjectClass
    lod2_multi_surface: typing.Optional[MultiSurface]
    def __repr__(self) -> builtins.str:
        ...


class AuxiliaryTrafficSpace:
    id: builtins.str
    bounded_by: typing.Optional[Envelope]
    city_object_class: CityObjectClass
    lod2_multi_surface: typing.Optional[MultiSurface]
    lod2_multi_curve: typing.Optional[MultiCurve]
    auxiliary_traffic_area: builtins.list[AuxiliaryTrafficArea]
    def __repr__(self) -> builtins.str:
        ...


class Building:
    id: builtins.str
    bounded_by: typing.Optional[Envelope]
    city_object_class: CityObjectClass
    storeys_above_ground: typing.Optional[builtins.int]
    storeys_below_ground: typing.Optional[builtins.int]
    lod1_solid: typing.Optional[Solid]
    lod2_solid: typing.Optional[Solid]
    lod3_solid: typing.Optional[Solid]
    lod0_multi_surface: typing.Optional[MultiSurface]
    lod2_multi_surface: typing.Optional[MultiSurface]
    lod3_multi_surface: typing.Optional[MultiSurface]
    wall_surface: builtins.list[WallSurface]
    roof_surface: builtins.list[RoofSurface]
    ground_surface: builtins.list[GroundSurface]
    def __repr__(self) -> builtins.str:
        ...


class CityFurniture:
    id: builtins.str
    bounded_by: typing.Optional[Envelope]
    city_object_class: CityObjectClass
    lod1_solid: typing.Optional[Solid]
    lod2_solid: typing.Optional[Solid]
    lod0_multi_surface: typing.Optional[MultiSurface]
    def __repr__(self) -> builtins.str:
        ...


class CityModel:
    def city_objects_len(self) -> builtins.int:
        ...

    def buildings(self) -> builtins.list[Building]:
        ...

    def roads(self) -> builtins.list[Road]:
        ...

    def solitary_vegetation_objects(self) -> builtins.list[SolitaryVegetationObject]:
        ...

    def city_furniture_objects(self) -> builtins.list[CityFurniture]:
        ...

    def relief_features(self) -> builtins.list[ReliefFeature]:
        ...

    def tin_reliefs(self) -> builtins.list[TinRelief]:
        ...

    def refresh_bounded_by_recursive(self) -> None:
        ...

    def __repr__(self) -> builtins.str:
        ...


class DirectPosition:
    x: builtins.float
    y: builtins.float
    z: builtins.float
    coords: tuple[builtins.float, builtins.float, builtins.float]
    def __repr__(self) -> builtins.str:
        ...


class DoorSurface:
    id: builtins.str
    bounded_by: typing.Optional[Envelope]
    city_object_class: CityObjectClass
    lod0_multi_surface: typing.Optional[MultiSurface]
    lod2_multi_surface: typing.Optional[MultiSurface]
    lod3_multi_surface: typing.Optional[MultiSurface]
    def __repr__(self) -> builtins.str:
        ...


class Envelope:
    lower_corner: tuple[builtins.float, builtins.float, builtins.float]
    upper_corner: tuple[builtins.float, builtins.float, builtins.float]
    size_x: builtins.float
    size_y: builtins.float
    size_z: builtins.float
    volume: builtins.float
    def contains(self, pos:DirectPosition) -> builtins.bool:
        ...

    def __repr__(self) -> builtins.str:
        ...


class GmlReader:
    def __new__(cls,path:builtins.str): ...
    def with_rebuild_object_bounds(self, rebuild:builtins.bool) -> GmlReader:
        ...

    def finish(self) -> CityModel:
        ...

    def __repr__(self) -> builtins.str:
        ...


class GroundSurface:
    id: builtins.str
    bounded_by: typing.Optional[Envelope]
    city_object_class: CityObjectClass
    lod0_multi_surface: typing.Optional[MultiSurface]
    lod2_multi_surface: typing.Optional[MultiSurface]
    lod3_multi_surface: typing.Optional[MultiSurface]
    def __repr__(self) -> builtins.str:
        ...


class Intersection:
    id: builtins.str
    bounded_by: typing.Optional[Envelope]
    city_object_class: CityObjectClass
    lod0_multi_curve: typing.Optional[MultiCurve]
    lod0_multi_surface: typing.Optional[MultiSurface]
    lod1_solid: typing.Optional[Solid]
    traffic_space: builtins.list[TrafficSpace]
    auxiliary_traffic_space: builtins.list[AuxiliaryTrafficSpace]
    def __repr__(self) -> builtins.str:
        ...


class LinearRing:
    points: builtins.list[DirectPosition]
    def __repr__(self) -> builtins.str:
        ...


class MultiCurve:
    def curves(self) -> builtins.list[builtins.list[DirectPosition]]:
        ...

    def compute_envelope(self) -> Envelope:
        ...

    def __repr__(self) -> builtins.str:
        ...


class MultiSurface:
    def polygons(self) -> builtins.list[Polygon]:
        ...

    def triangulate(self) -> TriangulatedSurface:
        ...

    def compute_envelope(self) -> Envelope:
        ...

    def __repr__(self) -> builtins.str:
        ...


class Polygon:
    exterior: typing.Optional[LinearRing]
    interior: builtins.list[LinearRing]
    def compute_envelope(self) -> typing.Optional[Envelope]:
        ...

    def __repr__(self) -> builtins.str:
        ...


class ReliefFeature:
    id: builtins.str
    bounded_by: typing.Optional[Envelope]
    city_object_class: CityObjectClass
    relief_component: builtins.list[TinRelief]
    def __repr__(self) -> builtins.str:
        ...


class Road:
    id: builtins.str
    bounded_by: typing.Optional[Envelope]
    city_object_class: CityObjectClass
    section: builtins.list[Section]
    intersection: builtins.list[Intersection]
    def __repr__(self) -> builtins.str:
        ...


class RoofSurface:
    id: builtins.str
    bounded_by: typing.Optional[Envelope]
    city_object_class: CityObjectClass
    lod0_multi_surface: typing.Optional[MultiSurface]
    lod2_multi_surface: typing.Optional[MultiSurface]
    lod3_multi_surface: typing.Optional[MultiSurface]
    def __repr__(self) -> builtins.str:
        ...


class Section:
    id: builtins.str
    bounded_by: typing.Optional[Envelope]
    city_object_class: CityObjectClass
    lod0_multi_curve: typing.Optional[MultiCurve]
    lod0_multi_surface: typing.Optional[MultiSurface]
    lod1_solid: typing.Optional[Solid]
    traffic_space: builtins.list[TrafficSpace]
    auxiliary_traffic_space: builtins.list[AuxiliaryTrafficSpace]
    def __repr__(self) -> builtins.str:
        ...


class Solid:
    def polygons(self) -> builtins.list[Polygon]:
        ...

    def triangulate(self) -> TriangulatedSurface:
        ...

    def compute_envelope(self) -> Envelope:
        ...

    def __repr__(self) -> builtins.str:
        ...


class SolitaryVegetationObject:
    id: builtins.str
    bounded_by: typing.Optional[Envelope]
    city_object_class: CityObjectClass
    lod1_solid: typing.Optional[Solid]
    lod2_solid: typing.Optional[Solid]
    lod0_multi_surface: typing.Optional[MultiSurface]
    lod1_implicit_representation: typing.Optional[DirectPosition]
    def __repr__(self) -> builtins.str:
        ...


class TinRelief:
    id: builtins.str
    bounded_by: typing.Optional[Envelope]
    city_object_class: CityObjectClass
    tin: TriangulatedSurface
    def __repr__(self) -> builtins.str:
        ...


class TrafficArea:
    id: builtins.str
    bounded_by: typing.Optional[Envelope]
    city_object_class: CityObjectClass
    lod2_multi_surface: typing.Optional[MultiSurface]
    def __repr__(self) -> builtins.str:
        ...


class TrafficSpace:
    id: builtins.str
    bounded_by: typing.Optional[Envelope]
    city_object_class: CityObjectClass
    lod2_multi_surface: typing.Optional[MultiSurface]
    lod2_multi_curve: typing.Optional[MultiCurve]
    traffic_area: builtins.list[TrafficArea]
    def __repr__(self) -> builtins.str:
        ...


class Triangle:
    a: DirectPosition
    b: DirectPosition
    c: DirectPosition
    def __repr__(self) -> builtins.str:
        ...


class TriangulatedSurface:
    triangles: builtins.list[Triangle]
    def compute_envelope(self) -> Envelope:
        ...

    def __repr__(self) -> builtins.str:
        ...


class WallSurface:
    id: builtins.str
    bounded_by: typing.Optional[Envelope]
    city_object_class: CityObjectClass
    lod0_multi_surface: typing.Optional[MultiSurface]
    lod2_multi_surface: typing.Optional[MultiSurface]
    lod3_multi_surface: typing.Optional[MultiSurface]
    door_surface: builtins.list[DoorSurface]
    window_surface: builtins.list[WindowSurface]
    def __repr__(self) -> builtins.str:
        ...


class WindowSurface:
    id: builtins.str
    bounded_by: typing.Optional[Envelope]
    city_object_class: CityObjectClass
    lod0_multi_surface: typing.Optional[MultiSurface]
    lod2_multi_surface: typing.Optional[MultiSurface]
    lod3_multi_surface: typing.Optional[MultiSurface]
    def __repr__(self) -> builtins.str:
        ...


class CityObjectClass(Enum):
    AuxiliaryTrafficArea = auto()
    AuxiliaryTrafficSpace = auto()
    Bridge = auto()
    BridgeConstructiveElement = auto()
    BridgeFurniture = auto()
    BridgeInstallation = auto()
    BridgePart = auto()
    BridgeRoom = auto()
    Building = auto()
    BuildingConstructiveElement = auto()
    BuildingFurniture = auto()
    BuildingInstallation = auto()
    BuildingPart = auto()
    BuildingRoom = auto()
    BuildingUnit = auto()
    CeilingSurface = auto()
    CityFurniture = auto()
    CityObjectGroup = auto()
    ClearanceSpace = auto()
    Door = auto()
    DoorSurface = auto()
    FloorSurface = auto()
    GenericLogicalSpace = auto()
    GenericOccupiedSpace = auto()
    GenericThematicSurface = auto()
    GenericUnoccupiedSpace = auto()
    GroundSurface = auto()
    Hole = auto()
    HoleSurface = auto()
    HollowSpace = auto()
    InteriorWallSurface = auto()
    Intersection = auto()
    Marking = auto()
    OtherConstruction = auto()
    OuterCeilingSurface = auto()
    OuterFloorSurface = auto()
    PlantCover = auto()
    Railway = auto()
    ReliefFeature = auto()
    Road = auto()
    RoofSurface = auto()
    Section = auto()
    SolitaryVegetationObject = auto()
    Square = auto()
    Story = auto()
    TinRelief = auto()
    Track = auto()
    TrafficArea = auto()
    TrafficSpace = auto()
    Tunnel = auto()
    TunnelConstructiveElement = auto()
    TunnelFurniture = auto()
    TunnelInstallation = auto()
    TunnelPart = auto()
    WallSurface = auto()
    WaterBody = auto()
    WaterGroundSurface = auto()
    WaterSurface = auto()
    Waterway = auto()
    Window = auto()
    WindowSurface = auto()

class LevelOfDetail(Enum):
    Zero = auto()
    One = auto()
    Two = auto()
    Three = auto()

