[workspace]
members = [
    "crates/*"
]

resolver = "2"

[workspace.package]
version = "0.0.1-alpha.3"
authors = ["Benedikt Schwab <benedikt.schwab@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/envis-space/ecitygml"

[workspace.dependencies]
egml = { version = "0.0.1-alpha.3" }

thiserror = "1.0.61"
clap = "4.5.9"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
nalgebra = "0.33.0"
serde = "1.0.204"
serde_yaml = "0.9"
quick-xml = "0.36.0"
itertools = "0.13.0"
