use ecitygml_core::model::common::CodeListValue;

/// The SIG3D standard code list `TransportationComplex_function.xml` (version 2.0).
///
/// <https://www.sig3d.de/codelists/standard/transportation/2.0/TransportationComplex_function.xml>
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Sig3dTransportationComplexFunctionValue {
    Road1000,
    FreewayMotorway,
    HighwayNationalPrimaryRoad,
    LandRoad,
    DistrictRoad,
    MunicipalRoad,
    MainThroughRoad,
    FreewayInterchangeHighwayJunction,
    Junction,
    Road1200,
    Driveway,
    FootpathFootway,
    HikingTrail,
    BikewayCyclePath,
    BridlewayBridlepath,
    MainAgriculturalRoad,
    AgriculturalRoad,
    BikewayFootway,
    AccessRoad,
    DeadEndRoad,
    Lane,
    LaneOneDirection,
    LaneBothDirection,
    PedestrianZone,
    Place,
    ParkingArea,
    Marketplace,
    ServiceArea,
    RailTransport,
    Rail,
    UrbanCityTrain,
    CityRailway,
    Tram,
    Subway,
    FunicularMountainRailway,
    MountainRailway,
    Chairlift,
    SkiLiftSkiTowLift,
    SuspensionRailway,
    RailwayTrack,
    MagneticLevitationTrain,
    RailwayStation,
    Stop,
    Station,
    PowerWheel,
    Airport,
    InternationalAirport,
    RegionalAirport,
    LandingPlace2130,
    Heliport,
    LandingPlace2150,
    GlidingAirfield,
    Taxiway,
    Apron,
    Runway,
    Canal,
    Harbor,
    PleasureCraftHarbour,
    Ferry2400,
    CarFerry,
    TrainFerry,
    Ferry2430,
    LandingStage,
    WaterwayIOrder,
    NavigableRiver,
    InlandNavigationWaterway02620,
    InlandNavigationWaterway02621,
    InlandNavigationWaterwayI,
    InlandNavigationWaterwayIi,
    InlandNavigationWaterwayIii,
    InlandNavigationWaterwayIv,
    InlandNavigationWaterwayV,
    InlandNavigationWaterwayVi,
    InlandNavigationWaterwayVii,
    MaritimeNavigation,
    NavigableLake,
    Others,
    /// A value within this code list's codeSpace that isn't one of the
    /// entries above.
    Other(String),
}

impl CodeListValue for Sig3dTransportationComplexFunctionValue {
    const CODE_SPACE: &'static str = "http://www.sig3d.org/codelists/citygml/2.0/transportation/2.0/TransportationComplex_function.xml";

    fn from_code_value(value: &str) -> Self {
        match value {
            "1000" => Self::Road1000,
            "1010" => Self::FreewayMotorway,
            "1020" => Self::HighwayNationalPrimaryRoad,
            "1030" => Self::LandRoad,
            "1040" => Self::DistrictRoad,
            "1050" => Self::MunicipalRoad,
            "1060" => Self::MainThroughRoad,
            "1100" => Self::FreewayInterchangeHighwayJunction,
            "1110" => Self::Junction,
            "1200" => Self::Road1200,
            "1210" => Self::Driveway,
            "1220" => Self::FootpathFootway,
            "1230" => Self::HikingTrail,
            "1240" => Self::BikewayCyclePath,
            "1250" => Self::BridlewayBridlepath,
            "1260" => Self::MainAgriculturalRoad,
            "1270" => Self::AgriculturalRoad,
            "1280" => Self::BikewayFootway,
            "1290" => Self::AccessRoad,
            "1300" => Self::DeadEndRoad,
            "1400" => Self::Lane,
            "1410" => Self::LaneOneDirection,
            "1420" => Self::LaneBothDirection,
            "1500" => Self::PedestrianZone,
            "1600" => Self::Place,
            "1610" => Self::ParkingArea,
            "1620" => Self::Marketplace,
            "1700" => Self::ServiceArea,
            "1800" => Self::RailTransport,
            "1805" => Self::Rail,
            "1810" => Self::UrbanCityTrain,
            "1815" => Self::CityRailway,
            "1820" => Self::Tram,
            "1825" => Self::Subway,
            "1830" => Self::FunicularMountainRailway,
            "1835" => Self::MountainRailway,
            "1840" => Self::Chairlift,
            "1845" => Self::SkiLiftSkiTowLift,
            "1850" => Self::SuspensionRailway,
            "1855" => Self::RailwayTrack,
            "1860" => Self::MagneticLevitationTrain,
            "1900" => Self::RailwayStation,
            "1910" => Self::Stop,
            "1920" => Self::Station,
            "2000" => Self::PowerWheel,
            "2100" => Self::Airport,
            "2110" => Self::InternationalAirport,
            "2120" => Self::RegionalAirport,
            "2130" => Self::LandingPlace2130,
            "2140" => Self::Heliport,
            "2150" => Self::LandingPlace2150,
            "2160" => Self::GlidingAirfield,
            "2170" => Self::Taxiway,
            "2180" => Self::Apron,
            "2190" => Self::Runway,
            "2200" => Self::Canal,
            "2300" => Self::Harbor,
            "2310" => Self::PleasureCraftHarbour,
            "2400" => Self::Ferry2400,
            "2410" => Self::CarFerry,
            "2420" => Self::TrainFerry,
            "2430" => Self::Ferry2430,
            "2500" => Self::LandingStage,
            "2600" => Self::WaterwayIOrder,
            "2610" => Self::NavigableRiver,
            "2620" => Self::InlandNavigationWaterway02620,
            "2621" => Self::InlandNavigationWaterway02621,
            "2622" => Self::InlandNavigationWaterwayI,
            "2623" => Self::InlandNavigationWaterwayIi,
            "2624" => Self::InlandNavigationWaterwayIii,
            "2625" => Self::InlandNavigationWaterwayIv,
            "2626" => Self::InlandNavigationWaterwayV,
            "2627" => Self::InlandNavigationWaterwayVi,
            "2628" => Self::InlandNavigationWaterwayVii,
            "2630" => Self::MaritimeNavigation,
            "2640" => Self::NavigableLake,
            "2700" => Self::Others,
            other => Self::Other(other.to_string()),
        }
    }

    fn to_code_value(&self) -> &str {
        match self {
            Self::Road1000 => "1000",
            Self::FreewayMotorway => "1010",
            Self::HighwayNationalPrimaryRoad => "1020",
            Self::LandRoad => "1030",
            Self::DistrictRoad => "1040",
            Self::MunicipalRoad => "1050",
            Self::MainThroughRoad => "1060",
            Self::FreewayInterchangeHighwayJunction => "1100",
            Self::Junction => "1110",
            Self::Road1200 => "1200",
            Self::Driveway => "1210",
            Self::FootpathFootway => "1220",
            Self::HikingTrail => "1230",
            Self::BikewayCyclePath => "1240",
            Self::BridlewayBridlepath => "1250",
            Self::MainAgriculturalRoad => "1260",
            Self::AgriculturalRoad => "1270",
            Self::BikewayFootway => "1280",
            Self::AccessRoad => "1290",
            Self::DeadEndRoad => "1300",
            Self::Lane => "1400",
            Self::LaneOneDirection => "1410",
            Self::LaneBothDirection => "1420",
            Self::PedestrianZone => "1500",
            Self::Place => "1600",
            Self::ParkingArea => "1610",
            Self::Marketplace => "1620",
            Self::ServiceArea => "1700",
            Self::RailTransport => "1800",
            Self::Rail => "1805",
            Self::UrbanCityTrain => "1810",
            Self::CityRailway => "1815",
            Self::Tram => "1820",
            Self::Subway => "1825",
            Self::FunicularMountainRailway => "1830",
            Self::MountainRailway => "1835",
            Self::Chairlift => "1840",
            Self::SkiLiftSkiTowLift => "1845",
            Self::SuspensionRailway => "1850",
            Self::RailwayTrack => "1855",
            Self::MagneticLevitationTrain => "1860",
            Self::RailwayStation => "1900",
            Self::Stop => "1910",
            Self::Station => "1920",
            Self::PowerWheel => "2000",
            Self::Airport => "2100",
            Self::InternationalAirport => "2110",
            Self::RegionalAirport => "2120",
            Self::LandingPlace2130 => "2130",
            Self::Heliport => "2140",
            Self::LandingPlace2150 => "2150",
            Self::GlidingAirfield => "2160",
            Self::Taxiway => "2170",
            Self::Apron => "2180",
            Self::Runway => "2190",
            Self::Canal => "2200",
            Self::Harbor => "2300",
            Self::PleasureCraftHarbour => "2310",
            Self::Ferry2400 => "2400",
            Self::CarFerry => "2410",
            Self::TrainFerry => "2420",
            Self::Ferry2430 => "2430",
            Self::LandingStage => "2500",
            Self::WaterwayIOrder => "2600",
            Self::NavigableRiver => "2610",
            Self::InlandNavigationWaterway02620 => "2620",
            Self::InlandNavigationWaterway02621 => "2621",
            Self::InlandNavigationWaterwayI => "2622",
            Self::InlandNavigationWaterwayIi => "2623",
            Self::InlandNavigationWaterwayIii => "2624",
            Self::InlandNavigationWaterwayIv => "2625",
            Self::InlandNavigationWaterwayV => "2626",
            Self::InlandNavigationWaterwayVi => "2627",
            Self::InlandNavigationWaterwayVii => "2628",
            Self::MaritimeNavigation => "2630",
            Self::NavigableLake => "2640",
            Self::Others => "2700",
            Self::Other(s) => s,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trips_known_codes() {
        for (code, value) in [
            ("1000", Sig3dTransportationComplexFunctionValue::Road1000),
            ("2700", Sig3dTransportationComplexFunctionValue::Others),
        ] {
            assert_eq!(
                Sig3dTransportationComplexFunctionValue::from_code_value(code),
                value
            );
            assert_eq!(value.to_code_value(), code);
        }
    }

    #[test]
    fn unrecognized_code_in_this_code_space_falls_back_to_other() {
        let value = Sig3dTransportationComplexFunctionValue::from_code_value("999999");
        assert_eq!(
            value,
            Sig3dTransportationComplexFunctionValue::Other("999999".to_string())
        );
        assert_eq!(value.to_code_value(), "999999");
    }
}
