use ecitygml_core::model::common::CodeListValue;

/// The SIG3D standard code list `SolitaryVegetationObject_species.xml` (version 2.0).
///
/// <https://www.sig3d.de/codelists/standard/vegetation/2.0/SolitaryVegetationObject_species.xml>
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Sig3dSpeciesValue {
    Picea,
    Pinus1010,
    Larix,
    Quercus1030,
    Fagus,
    Betula,
    Alnus,
    Populus1070,
    Salix1080,
    Acer1090,
    Fraxinus,
    Arabis,
    GaleobdolonLuteum,
    CampanulaPoscharskyana,
    GaliumOdoratum,
    AlliumUrsinum,
    Helleborus1160,
    Alchemilla,
    Iris,
    Begonia,
    RanunculusAsiaticus,
    GeraniumMacrorrhizumIngwersen,
    PelargonieBurcDouble,
    Euphorbia,
    Aqulilegia,
    SymphytumOfficinale,
    SedumSpectabileUndSedumTelphium,
    Centaurea,
    CentaureaCysanus,
    LychnisCoronaria,
    Physalis,
    CoreopsisVerticillata,
    Calendula,
    PhloxPaniculata,
    DianthusBarbatus,
    Hemerocallis,
    HemerocallisFlava,
    Lythrum,
    Lysmachia,
    AsterNovae,
    CardiocrinumGiganteum,
    Delphinium,
    Pteridium,
    GymnocarpiumDryopteris,
    MatteucciaStruthiopteris,
    MagnoliaElisabeth,
    Hibiskus,
    Hydrangea1470,
    CotinusCoggygria1480,
    EuonymusEuropea,
    Rhododendron1500,
    Pontederia,
    Clematis1520,
    Tropaeolum,
    ViciaLathyrus,
    Plumbago,
    Zantedeschia,
    Fuchsia1570,
    Gerbera1580,
    Nopalxochia,
    Hydrangea1600,
    Cassia,
    Cistus,
    AbienusFestuschristus,
    AbiesAlba,
    AbiesCephalonica,
    AbiesConcolor,
    AbiesGrandis,
    AbiesHomolepsis,
    AbiesKoreana,
    AbiesLasiocarpa,
    AbiesNordmanniana,
    AbiesPinsapo,
    AbiesProcera,
    AbiesProceraGlauca,
    AbiesVeitchii,
    AcerCampStre,
    AcerCapillipes,
    AcerCappadocicum,
    AcerCircinatum,
    AcerDavidii,
    AcerGinnalaMaxim,
    AcerGrosserii,
    AcerMonspessulanum,
    AcerNegundo,
    AcerPalmatum,
    AcerPlatanoides,
    AcerPlatanoidesCrimsonKing,
    AcerPseudoplatanus,
    AcerRubrum,
    AcerSaccharinum,
    AcerSaccharumMarsch,
    AcerTartaricum,
    AesculusHippocStanum,
    AesculusXCarnea,
    AfzeliaAfricana,
    AilanthusAltissima,
    AlnusCordata,
    AlnusGlutinosa,
    AlnusIncNa,
    AlnusViridis,
    AmelNchierOvLis,
    AnacardiumOccidentale,
    AraliaElata,
    AraucariaAraucana,
    AucubaJaponica,
    BerberisJulianae,
    BerberisThunbergii,
    BetulaAlnoides,
    BetulaCostata,
    BetulaDavurica,
    BetulaErmanii,
    BetulaPapyrifera,
    BTulaPNdula,
    BetulaPubescens,
    BroussonetiaPapyrifera,
    BuddlejaDavidii,
    ButyrospermumParkii,
    BuxusSempervirens,
    CalocedrusDecurrens,
    CalocedrusDecurrensAureovariegata,
    CalycanthusFloridus,
    CampsisRadicans,
    CaraganaArborescens,
    CarpNusBTulus,
    CassiaSiberiana,
    CastanASatVa,
    CatalpaBignonioides,
    CedrelaSinensis,
    CedrusAtlantica,
    CedrusAtlanticaGlauca,
    CedrusDeodara,
    CedrusDeodaraVarPaktia,
    CedrusLibani,
    CeltisOccidentalis,
    CercisSiliquastrum,
    ChaenomelesJaponica,
    ChamaecyparisLawsonia,
    ChamaecyparisNootkatensis,
    ChionanthusVirginicus,
    CladrastisLutea,
    ClematisMontana,
    ClematisVitalba,
    ColuteaArborescens,
    CornusAlba,
    CornusFlorida,
    CornusMas,
    CornusSanguinea,
    CRylusAvellNa,
    CorylusAvellanaContorta,
    CRylusColRna,
    CorylusMaxima,
    CotinusCoggygria2520,
    CotoneasterFrigidus,
    CrataegusLaevigata,
    CrataegusLaevigataPaulsScarlet,
    CrataegusLavalleiCarrierei,
    CrataegusMonogyna,
    CryptomeriaJaponica,
    CupressusArizonica,
    CupressusSempervirens,
    DavidiaInvolucrata,
    DelonixRegia,
    DeutziaScabra,
    DracaenaDraco,
    ElaeagnusAngustifolia,
    ElaeagnusUmbellata,
    EuonymusAlatus,
    EuonymusEuropaeus,
    EuonymusPlanipes,
    FagusOrientalis,
    FagusSylvatica,
    FagusSylvaticaPendula,
    FGusSylvTicaPurpurA,
    FicusCarica2740,
    ForsythiaXIntermedia,
    FrangulaAlnus,
    FraxNusExcLsior,
    FraxinusLatifolia,
    FraxinusOrnus,
    FraxinusPaxiana,
    GinkgoBilobaL,
    GleditsiaTriacanthos,
    HalesiaCarolina,
    HamamelisVirginiana,
    HamamelisXIntermedia,
    HederaHelix,
    HibiscusSyriacus,
    HippophaeRhamnoides,
    IlexAquifolium,
    JasminumNudiflorum,
    JuglansNigra,
    JuglansRegia,
    JuniperusCommunis,
    JuniperusSabina,
    KerriaJaponicaPleniflora,
    KhayaSenegalensis,
    KoelreuteriaPaniculata,
    KolkwitziaAmabilis,
    LaburnumAlpinum,
    LaburnumAnagyroides,
    LarixDecidua,
    LarixKaempferi,
    LigustrumVulgare,
    LiquidambarOrientalis,
    LiquidambarStyraciflua3050,
    LiriodendronTulipifera,
    LoniceraMaackii,
    LoniceraTartarica,
    LoniceraXHeckrottii,
    LoniceraXylosteum,
    MagnoliaXSoulangiana,
    MahoniaAquifolium,
    MalusFloribunda,
    MLusSylvStris,
    MalusToringoides,
    MespilusGermanica,
    MetasequoiaGlyptostroboides,
    OstryaCarpinifolia,
    ParrotiaPersica,
    ParthenocissusQuinquefolia,
    ParthenocissusTricuspidata,
    PaulowniaTomentosa,
    PhiladelphusCoronarius,
    PiceaAbies,
    PiceaAbiesInversa,
    PiceaAsperata,
    PiceaEngelmanii,
    PiceaGlauca,
    PiceaGlaucaConica,
    PiceaOmorika,
    PiceaOrientalis,
    PiceaPolita,
    PiceaPungensGlauca,
    PiceaSitchensis,
    PinusAristata,
    PinusArmandii,
    PinusCembra,
    PinusContorta,
    PinusHeldreichii,
    PinusJeffreyi,
    PinusKoraiensis,
    PinusLeucodermis,
    PinusMugo,
    PinusNigra,
    PinusNigraVar3450,
    PinusNigraVar3460,
    PinusParviflora,
    PinusPeuce,
    PinusPonderosa,
    PinusStrobus,
    PinusSylvestris,
    PinusThunbergii,
    PinusWallichiana,
    PlatanusAcerifolia,
    PlatanusOrientalis,
    PlatycladusOrientalis,
    PopulusAlba,
    PopulusNigra,
    PopulusSimonii,
    PopulusTremula,
    PopulusXCanadensis,
    PopulusXCanescens,
    PrunusAvium3630,
    PrunusCerasiferaNigra,
    PrunusDomestica3650,
    PrunusDomesticaSsp,
    PrunusDulcis,
    PrunusLaurocerasus,
    PrNusPDus,
    PrunusSargentii,
    PrunusSerotina,
    PrunusSerrulata,
    PrunusSpinosa3730,
    PrunusSubhirtella,
    PseudotsugaMenziesii,
    PteleaTrifoliata,
    PterocaryaFraxinifolia,
    PterocaryaStenoptera,
    PyracanthaCoccinea,
    PRusPyrSter,
    QuercusAcutissima,
    QuercusCerris,
    QuercusCoccinea,
    QuercusFrainetto,
    QuercusIlex,
    QuercusLibani,
    QuercusPalustris,
    QuercusPetraea,
    QuercusPrinus,
    QuercusPubescens,
    QuercusRobur,
    QuercusRubra,
    QuercusSuber,
    QuercusXHispanicaLucombeana,
    QuercusXTurneri,
    RhamnusCathartica,
    RhamnusImeretinus,
    RhodotyposScandens,
    RhusHirta,
    RibesAureum,
    RibesSanguineum,
    RobiniaPseudoacacia,
    RosaCanina,
    RosaSpinosissima,
    RubusFruticosus,
    SalixAlba,
    SalixAlbaTristis,
    SalixAurita,
    SalixBabylonica,
    SalixCaprea,
    SalixCapreaKilmarnock,
    SalixCinerea,
    SalixFragilis,
    SalixMatsudanaTortuosa,
    SalixViminalis,
    SambucusNigra,
    SambucusRacemosa,
    SciadopitysVerticillata,
    SequoiaSempervirens,
    SequoiadendronGiganteum,
    ShepherdiaArgentea,
    SophoraJaponica,
    SorbusAria,
    SRbusAucupRia,
    SorbusDomestica,
    SorbusIntermedia,
    SorbusTorminalis,
    SpiraeaXBillardii,
    SpiraeaXVanhouttei,
    StaphyleaPinnata,
    StranvaesiaDavidiana,
    SymphoricarposAlbus,
    SyringaReflexa,
    SyringaVulgaris,
    TamarixParviflora,
    TaxodiumDistichum,
    TaxusBaccata,
    ThujaOccidentalis,
    ThujaPlicata,
    ThujopsisDolabrata,
    TLiaCordTa,
    TiliaPlatyphyllos,
    TiliaTomentosa,
    TsugaCanadensis,
    UlexEuropaeus,
    LmusGlBra,
    UlmusLaevis,
    LmusMNor,
    UlmusPumila,
    ViburnumFarreri,
    ViburnumLantana,
    ViburnumLentago,
    ViburnumOpulus,
    ViburnumRhytidophyllum,
    ViburnumTinus,
    ViburnumXBodnantense,
    ViscumAlbum,
    VitisCoignetiae,
    WeigelaFlorida,
    WisteriaSinensis,
    ZelkovaSerrata,
    Acer4620,
    ActinidiaLind,
    AeschynanthusJack,
    Ageratum,
    AgrostemmaGithago,
    Agrostis,
    AlliumCepa,
    AlliumFistulosum,
    AlliumPorrum,
    AlliumSchoenoprasum,
    Aloe,
    AlonsoaMeridionalisFOKuntze,
    AlopecurusPratensis,
    Alstroemeria,
    AmaranthusBlitoidesSWatson,
    AmaranthusCruentus,
    AnigozanthosLabil,
    AnthriscusCerefoliumHoffm,
    AnthuriumSchott,
    Antirrhinum,
    ApiumGraveolens,
    Arctium,
    ArgyranthemumFrutescensSchultzBip,
    ArnicaMontana,
    AroniaMedik,
    ArrhenatherumElatiusPBeauvExJSEtKBPresl,
    AsparagusOfficinalis,
    Aster,
    AubrietaAdans,
    AvenaSativa4910,
    AvenaSativa4920,
    BegoniaXHiemalisFotsch,
    BegoniaXTuberhybridaVoss,
    BegoniaSemperflorensHybriden,
    BetaVulgarisVarAltissimaDLl,
    BetaVulgarisVarConditivaAlef,
    BetaVulgarisVarCrassaMansf,
    BetaVulgarisVarVulgaris,
    BidensFerulifoliaJacqDc,
    BrachyscomeCass,
    BrassicaJunceaCzernjEtCosson,
    BrassicaNapusPartim5030,
    BrassicaNapusPartim5040,
    BrassicaNapusVarNapobrassicaRchb,
    BrassicaOleraceaConvarAcephalaDcAlefVarGongylodes,
    BrassicaOleraceaConvarAcephalaDcAlefVarMedullosaThelUndVarViridis,
    BrassicaOleraceaConvarAcephalaDcAlefVarSabellica,
    BrassicaOleraceaConvarBotrytisAlefVarBotrytis,
    BrassicaOleraceaConvarBotrytisAlefVarCymosaDuch,
    BrassicaOleraceaConvarCapitataAlefVarAlbaDc,
    BrassicaOleraceaConvarCapitataAlefVarRubraDc,
    BrassicaOleraceaConvarCapitataAlefVarSabauda,
    BrassicaOleraceaConvarOleraceaVarGemmiferaDc,
    BrassicaRapaVarRapa5150,
    BrassicaRapaVarRapa5160,
    BrassicaRapaVarSilvestrisLamBriggs5170,
    BrassicaRapaVarSilvestrisLamBriggs5180,
    Bromus,
    BrunneraMacrophyllaAdamsJohnst,
    Calceolaria,
    CallunaVulgarisHull,
    CamelinaSativaCrantz,
    CannabisSativa,
    CapsicumAnnuum,
    Carex,
    CarthamusTinctorius,
    Celosia,
    ChamomillaRecutitaRauschert,
    CichoriumEndivia,
    Clematis5310,
    ConvallariaMajalis,
    CoronillaVaria,
    Corylus,
    CrassulaSchmidtiiRegel,
    CucumisSativus,
    Cucurbita,
    CucurbitaPepo,
    CupheaPBr,
    CydoniaOblongaMil,
    CynaraCardunculus,
    CynaraScolymus,
    DaboeciaCantabricaHudsKKoch,
    Dactylis,
    DahliaCav,
    DaucusCarota5460,
    DaucusCarota5470,
    DendranthemaXGrandiflorumRamatKitam,
    DeschampsiaCespitosaPBeauv,
    Dianthus,
    Digitalis,
    DracocephalumMoldavica,
    EchinodorusCRichExEngelm,
    Erica,
    EuonymusFortuneiTurczHandMazz,
    EuphorbiaFulgensKarwExKlotzsch,
    EuphorbiaMiliiDesMouVarMilii,
    EuphorbiaPulcherrimaWilldExKlotzsch,
    FagopyrumMil,
    FestucaArundinaceaSchreber,
    FestucaOvinaSensuLato,
    FestucaPratensisHudson,
    FestucaRubraSensuLato,
    FicusBenjamina,
    FicusCarica5650,
    FoeniculumVulgareMil5660,
    FoeniculumVulgareMil5670,
    ForsythiaVahl,
    Fragaria,
    Fuchsia5700,
    GazaniaHybriden,
    Gentiana,
    Gerbera5730,
    GinkgoBiloba,
    GlycineMaxMerr,
    HebeCommExJuss,
    HelianthusAnnuus,
    HelianthusTuberosus,
    HelichrysumItalicumRothGussone,
    HeliotropiumArborescens,
    Helleborus5810,
    Hippophae,
    HordeumVulgareSensuLato5830,
    HordeumVulgareSensuLato5840,
    HumulusLupulus,
    Hydrangea5860,
    HypericumAndrosaemum,
    HypericumPerforatum,
    HyssopusOfficinalis,
    Ilex,
    Impatiens,
    ImpatiensWallerianaHybriden,
    JuglansHybriden,
    KalanchoeAdans,
    LactucaSativa5950,
    LactucaSativa5960,
    LeontopodiumAlpinumCass,
    LeucanthemumXSuperbumJWIngramBergmansExKent,
    Lilium,
    LimoniumMil,
    LinumUsitatissimum,
    LiquidambarStyraciflua6020,
    Lobelia,
    LoliumPartim,
    LoliumMultiflorumLam,
    LoliumPerenne,
    LoliumXBoucheanumKunth,
    LoniceraNitidaWils,
    LotusCorniculatus,
    LupinusLuteus,
    LupinusAlbus,
    LupinusAngustifolius,
    LupinusMutabilis,
    LupinusNanusDouglas,
    LycopersiconLycopersicumKarstenExFarw,
    MalusMil6160,
    MalusMil6170,
    MalusMil6180,
    MalvaVerticillata,
    MedicagoLupulina,
    MedicagoSativa,
    MelissaOfficinalis,
    Nicotiana,
    OcimumBasilicum,
    OnobrychisViciifoliaScop,
    Orchidaceae,
    OriganumMajorana,
    OriganumVulgare,
    PelargoniumLhRitExAit,
    PelargoniumGrandiflorumHybriden,
    PetroselinumCrispumMillerNymanExAWHill6310,
    PetroselinumCrispumMillerNymanExAWHill6320,
    PetuniaJuss,
    PhaceliaJuss,
    PhalarisArundinacea,
    PhaseolusCoccineus,
    PhaseolusVulgaris6370,
    PhaseolusVulgaris6380,
    Phleum,
    PhysocarpusCambessMaxim,
    PiceaADietr,
    Pinus6420,
    PisumSativumPartim6430,
    PisumSativumPartim6440,
    PisumSativumPartim6450,
    PisumSativumPartim6460,
    Poa,
    PoaPratensis,
    Populus6490,
    Prunus6500,
    Prunus6510,
    PrunusAvium6520,
    PrunusCerasus,
    PrunusDomestica6540,
    PrunusPersicaBatsch,
    PrunusSpinosa6560,
    PyracanthaMJRoem,
    Pyrus6580,
    Pyrus6590,
    Quercus6600,
    Raphanobrassica,
    RaphanusSativusVarNigerMillerSKerner,
    RaphanusSativusVarOleiformisPers,
    RaphanusSativusVarSativus,
    RehmanniaLiboschExFischEtCAMey,
    Rhododendron6660,
    RhododendronSimsiiPlanch,
    Ribes6680,
    Ribes6690,
    RibesNigrum,
    RibesXNidigrolariaREtABauer,
    Rosa,
    Rubus6730,
    Rubus6740,
    SaintpauliaHWend,
    Salix6760,
    SanvitaliaLam,
    SaturejaHortensis,
    ScorzoneraHispanica,
    Secale6800,
    Secale6810,
    SilybumMarianumGaertn,
    SinapisAlba,
    SinningiaNees,
    Solanum,
    SolanumTuberosum,
    SpinaciaOleracea,
    StreptocarpusLind,
    SuteraRoth,
    SymphoricarposDuham,
    Syringa,
    Tagetes,
    TanacetumPartheniumSchultzBip,
    Tilia,
    TrifoliumAlexandrinum,
    TrifoliumHybridum,
    TrifoliumIncarnatum,
    TrifoliumPratense,
    TrifoliumRepens,
    TrifoliumResupinatum,
    TrisetumFlavescensPBeauv,
    TriticumAestivumEmendFioriEtPao7020,
    TriticumAestivumEmendFioriEtPao7030,
    TriticumDurumDesf,
    TriticumMonococcum,
    TriticumSpelta,
    Tulipa,
    TussilagoFarfara,
    Ulmus,
    Urtica,
    Vaccinium,
    ValerianaOfficinalis,
    ValerianellaLocustaLaterr,
    Vallisneria,
    ViciaPartim,
    ViciaFabaPartim7160,
    ViciaFabaPartim7170,
    ViciaSativa,
    VincaMinor,
    VitexAgnusCastus,
    Vitis,
    VitisVinifera,
    VrieseaSplendensBrongnLem,
    ZantedeschiaSpreng,
    ZeaMays,
    XFestulolium,
    XTriticosecaleWittm7270,
    XTriticosecaleWittm7280,
    Unknown,
    /// A value within this code list's codeSpace that isn't one of the
    /// entries above.
    Other(String),
}

impl CodeListValue for Sig3dSpeciesValue {
    const CODE_SPACE: &'static str = "http://www.sig3d.org/codelists/citygml/2.0/vegetation/2.0/SolitaryVegetationObject_species.xml";

    fn from_code_value(value: &str) -> Self {
        match value {
            "1000" => Self::Picea,
            "1010" => Self::Pinus1010,
            "1020" => Self::Larix,
            "1030" => Self::Quercus1030,
            "1040" => Self::Fagus,
            "1050" => Self::Betula,
            "1060" => Self::Alnus,
            "1070" => Self::Populus1070,
            "1080" => Self::Salix1080,
            "1090" => Self::Acer1090,
            "1100" => Self::Fraxinus,
            "1110" => Self::Arabis,
            "1120" => Self::GaleobdolonLuteum,
            "1130" => Self::CampanulaPoscharskyana,
            "1140" => Self::GaliumOdoratum,
            "1150" => Self::AlliumUrsinum,
            "1160" => Self::Helleborus1160,
            "1170" => Self::Alchemilla,
            "1180" => Self::Iris,
            "1190" => Self::Begonia,
            "1200" => Self::RanunculusAsiaticus,
            "1210" => Self::GeraniumMacrorrhizumIngwersen,
            "1220" => Self::PelargonieBurcDouble,
            "1230" => Self::Euphorbia,
            "1240" => Self::Aqulilegia,
            "1250" => Self::SymphytumOfficinale,
            "1260" => Self::SedumSpectabileUndSedumTelphium,
            "1270" => Self::Centaurea,
            "1280" => Self::CentaureaCysanus,
            "1290" => Self::LychnisCoronaria,
            "1300" => Self::Physalis,
            "1310" => Self::CoreopsisVerticillata,
            "1320" => Self::Calendula,
            "1330" => Self::PhloxPaniculata,
            "1340" => Self::DianthusBarbatus,
            "1350" => Self::Hemerocallis,
            "1360" => Self::HemerocallisFlava,
            "1370" => Self::Lythrum,
            "1380" => Self::Lysmachia,
            "1390" => Self::AsterNovae,
            "1400" => Self::CardiocrinumGiganteum,
            "1410" => Self::Delphinium,
            "1420" => Self::Pteridium,
            "1430" => Self::GymnocarpiumDryopteris,
            "1440" => Self::MatteucciaStruthiopteris,
            "1450" => Self::MagnoliaElisabeth,
            "1460" => Self::Hibiskus,
            "1470" => Self::Hydrangea1470,
            "1480" => Self::CotinusCoggygria1480,
            "1490" => Self::EuonymusEuropea,
            "1500" => Self::Rhododendron1500,
            "1510" => Self::Pontederia,
            "1520" => Self::Clematis1520,
            "1530" => Self::Tropaeolum,
            "1540" => Self::ViciaLathyrus,
            "1550" => Self::Plumbago,
            "1560" => Self::Zantedeschia,
            "1570" => Self::Fuchsia1570,
            "1580" => Self::Gerbera1580,
            "1590" => Self::Nopalxochia,
            "1600" => Self::Hydrangea1600,
            "1610" => Self::Cassia,
            "1620" => Self::Cistus,
            "1630" => Self::AbienusFestuschristus,
            "1640" => Self::AbiesAlba,
            "1650" => Self::AbiesCephalonica,
            "1660" => Self::AbiesConcolor,
            "1670" => Self::AbiesGrandis,
            "1680" => Self::AbiesHomolepsis,
            "1690" => Self::AbiesKoreana,
            "1700" => Self::AbiesLasiocarpa,
            "1710" => Self::AbiesNordmanniana,
            "1720" => Self::AbiesPinsapo,
            "1730" => Self::AbiesProcera,
            "1740" => Self::AbiesProceraGlauca,
            "1750" => Self::AbiesVeitchii,
            "1760" => Self::AcerCampStre,
            "1770" => Self::AcerCapillipes,
            "1780" => Self::AcerCappadocicum,
            "1790" => Self::AcerCircinatum,
            "1800" => Self::AcerDavidii,
            "1810" => Self::AcerGinnalaMaxim,
            "1820" => Self::AcerGrosserii,
            "1830" => Self::AcerMonspessulanum,
            "1840" => Self::AcerNegundo,
            "1850" => Self::AcerPalmatum,
            "1860" => Self::AcerPlatanoides,
            "1870" => Self::AcerPlatanoidesCrimsonKing,
            "1880" => Self::AcerPseudoplatanus,
            "1890" => Self::AcerRubrum,
            "1900" => Self::AcerSaccharinum,
            "1910" => Self::AcerSaccharumMarsch,
            "1920" => Self::AcerTartaricum,
            "1930" => Self::AesculusHippocStanum,
            "1940" => Self::AesculusXCarnea,
            "1950" => Self::AfzeliaAfricana,
            "1960" => Self::AilanthusAltissima,
            "1970" => Self::AlnusCordata,
            "1980" => Self::AlnusGlutinosa,
            "1990" => Self::AlnusIncNa,
            "2000" => Self::AlnusViridis,
            "2010" => Self::AmelNchierOvLis,
            "2020" => Self::AnacardiumOccidentale,
            "2030" => Self::AraliaElata,
            "2040" => Self::AraucariaAraucana,
            "2050" => Self::AucubaJaponica,
            "2060" => Self::BerberisJulianae,
            "2070" => Self::BerberisThunbergii,
            "2080" => Self::BetulaAlnoides,
            "2090" => Self::BetulaCostata,
            "2100" => Self::BetulaDavurica,
            "2110" => Self::BetulaErmanii,
            "2120" => Self::BetulaPapyrifera,
            "2130" => Self::BTulaPNdula,
            "2140" => Self::BetulaPubescens,
            "2150" => Self::BroussonetiaPapyrifera,
            "2160" => Self::BuddlejaDavidii,
            "2170" => Self::ButyrospermumParkii,
            "2180" => Self::BuxusSempervirens,
            "2190" => Self::CalocedrusDecurrens,
            "2200" => Self::CalocedrusDecurrensAureovariegata,
            "2210" => Self::CalycanthusFloridus,
            "2220" => Self::CampsisRadicans,
            "2230" => Self::CaraganaArborescens,
            "2240" => Self::CarpNusBTulus,
            "2250" => Self::CassiaSiberiana,
            "2260" => Self::CastanASatVa,
            "2270" => Self::CatalpaBignonioides,
            "2280" => Self::CedrelaSinensis,
            "2290" => Self::CedrusAtlantica,
            "2300" => Self::CedrusAtlanticaGlauca,
            "2310" => Self::CedrusDeodara,
            "2320" => Self::CedrusDeodaraVarPaktia,
            "2330" => Self::CedrusLibani,
            "2340" => Self::CeltisOccidentalis,
            "2350" => Self::CercisSiliquastrum,
            "2360" => Self::ChaenomelesJaponica,
            "2370" => Self::ChamaecyparisLawsonia,
            "2380" => Self::ChamaecyparisNootkatensis,
            "2390" => Self::ChionanthusVirginicus,
            "2400" => Self::CladrastisLutea,
            "2410" => Self::ClematisMontana,
            "2420" => Self::ClematisVitalba,
            "2430" => Self::ColuteaArborescens,
            "2440" => Self::CornusAlba,
            "2450" => Self::CornusFlorida,
            "2460" => Self::CornusMas,
            "2470" => Self::CornusSanguinea,
            "2480" => Self::CRylusAvellNa,
            "2490" => Self::CorylusAvellanaContorta,
            "2500" => Self::CRylusColRna,
            "2510" => Self::CorylusMaxima,
            "2520" => Self::CotinusCoggygria2520,
            "2530" => Self::CotoneasterFrigidus,
            "2540" => Self::CrataegusLaevigata,
            "2550" => Self::CrataegusLaevigataPaulsScarlet,
            "2560" => Self::CrataegusLavalleiCarrierei,
            "2570" => Self::CrataegusMonogyna,
            "2580" => Self::CryptomeriaJaponica,
            "2590" => Self::CupressusArizonica,
            "2600" => Self::CupressusSempervirens,
            "2610" => Self::DavidiaInvolucrata,
            "2620" => Self::DelonixRegia,
            "2630" => Self::DeutziaScabra,
            "2640" => Self::DracaenaDraco,
            "2650" => Self::ElaeagnusAngustifolia,
            "2660" => Self::ElaeagnusUmbellata,
            "2670" => Self::EuonymusAlatus,
            "2680" => Self::EuonymusEuropaeus,
            "2690" => Self::EuonymusPlanipes,
            "2700" => Self::FagusOrientalis,
            "2710" => Self::FagusSylvatica,
            "2720" => Self::FagusSylvaticaPendula,
            "2730" => Self::FGusSylvTicaPurpurA,
            "2740" => Self::FicusCarica2740,
            "2750" => Self::ForsythiaXIntermedia,
            "2760" => Self::FrangulaAlnus,
            "2770" => Self::FraxNusExcLsior,
            "2780" => Self::FraxinusLatifolia,
            "2790" => Self::FraxinusOrnus,
            "2800" => Self::FraxinusPaxiana,
            "2810" => Self::GinkgoBilobaL,
            "2820" => Self::GleditsiaTriacanthos,
            "2830" => Self::HalesiaCarolina,
            "2840" => Self::HamamelisVirginiana,
            "2850" => Self::HamamelisXIntermedia,
            "2860" => Self::HederaHelix,
            "2870" => Self::HibiscusSyriacus,
            "2880" => Self::HippophaeRhamnoides,
            "2890" => Self::IlexAquifolium,
            "2900" => Self::JasminumNudiflorum,
            "2910" => Self::JuglansNigra,
            "2920" => Self::JuglansRegia,
            "2930" => Self::JuniperusCommunis,
            "2940" => Self::JuniperusSabina,
            "2950" => Self::KerriaJaponicaPleniflora,
            "2960" => Self::KhayaSenegalensis,
            "2970" => Self::KoelreuteriaPaniculata,
            "2980" => Self::KolkwitziaAmabilis,
            "2990" => Self::LaburnumAlpinum,
            "3000" => Self::LaburnumAnagyroides,
            "3010" => Self::LarixDecidua,
            "3020" => Self::LarixKaempferi,
            "3030" => Self::LigustrumVulgare,
            "3040" => Self::LiquidambarOrientalis,
            "3050" => Self::LiquidambarStyraciflua3050,
            "3060" => Self::LiriodendronTulipifera,
            "3070" => Self::LoniceraMaackii,
            "3080" => Self::LoniceraTartarica,
            "3090" => Self::LoniceraXHeckrottii,
            "3100" => Self::LoniceraXylosteum,
            "3110" => Self::MagnoliaXSoulangiana,
            "3120" => Self::MahoniaAquifolium,
            "3130" => Self::MalusFloribunda,
            "3140" => Self::MLusSylvStris,
            "3150" => Self::MalusToringoides,
            "3160" => Self::MespilusGermanica,
            "3170" => Self::MetasequoiaGlyptostroboides,
            "3180" => Self::OstryaCarpinifolia,
            "3190" => Self::ParrotiaPersica,
            "3200" => Self::ParthenocissusQuinquefolia,
            "3210" => Self::ParthenocissusTricuspidata,
            "3220" => Self::PaulowniaTomentosa,
            "3230" => Self::PhiladelphusCoronarius,
            "3240" => Self::PiceaAbies,
            "3250" => Self::PiceaAbiesInversa,
            "3260" => Self::PiceaAsperata,
            "3270" => Self::PiceaEngelmanii,
            "3280" => Self::PiceaGlauca,
            "3290" => Self::PiceaGlaucaConica,
            "3300" => Self::PiceaOmorika,
            "3310" => Self::PiceaOrientalis,
            "3320" => Self::PiceaPolita,
            "3330" => Self::PiceaPungensGlauca,
            "3340" => Self::PiceaSitchensis,
            "3350" => Self::PinusAristata,
            "3360" => Self::PinusArmandii,
            "3370" => Self::PinusCembra,
            "3380" => Self::PinusContorta,
            "3390" => Self::PinusHeldreichii,
            "3400" => Self::PinusJeffreyi,
            "3410" => Self::PinusKoraiensis,
            "3420" => Self::PinusLeucodermis,
            "3430" => Self::PinusMugo,
            "3440" => Self::PinusNigra,
            "3450" => Self::PinusNigraVar3450,
            "3460" => Self::PinusNigraVar3460,
            "3470" => Self::PinusParviflora,
            "3480" => Self::PinusPeuce,
            "3490" => Self::PinusPonderosa,
            "3500" => Self::PinusStrobus,
            "3510" => Self::PinusSylvestris,
            "3520" => Self::PinusThunbergii,
            "3530" => Self::PinusWallichiana,
            "3540" => Self::PlatanusAcerifolia,
            "3550" => Self::PlatanusOrientalis,
            "3560" => Self::PlatycladusOrientalis,
            "3570" => Self::PopulusAlba,
            "3580" => Self::PopulusNigra,
            "3590" => Self::PopulusSimonii,
            "3600" => Self::PopulusTremula,
            "3610" => Self::PopulusXCanadensis,
            "3620" => Self::PopulusXCanescens,
            "3630" => Self::PrunusAvium3630,
            "3640" => Self::PrunusCerasiferaNigra,
            "3650" => Self::PrunusDomestica3650,
            "3660" => Self::PrunusDomesticaSsp,
            "3670" => Self::PrunusDulcis,
            "3680" => Self::PrunusLaurocerasus,
            "3690" => Self::PrNusPDus,
            "3700" => Self::PrunusSargentii,
            "3710" => Self::PrunusSerotina,
            "3720" => Self::PrunusSerrulata,
            "3730" => Self::PrunusSpinosa3730,
            "3740" => Self::PrunusSubhirtella,
            "3750" => Self::PseudotsugaMenziesii,
            "3760" => Self::PteleaTrifoliata,
            "3770" => Self::PterocaryaFraxinifolia,
            "3780" => Self::PterocaryaStenoptera,
            "3790" => Self::PyracanthaCoccinea,
            "3800" => Self::PRusPyrSter,
            "3810" => Self::QuercusAcutissima,
            "3820" => Self::QuercusCerris,
            "3830" => Self::QuercusCoccinea,
            "3840" => Self::QuercusFrainetto,
            "3850" => Self::QuercusIlex,
            "3860" => Self::QuercusLibani,
            "3870" => Self::QuercusPalustris,
            "3880" => Self::QuercusPetraea,
            "3890" => Self::QuercusPrinus,
            "3900" => Self::QuercusPubescens,
            "3910" => Self::QuercusRobur,
            "3920" => Self::QuercusRubra,
            "3930" => Self::QuercusSuber,
            "3940" => Self::QuercusXHispanicaLucombeana,
            "3950" => Self::QuercusXTurneri,
            "3960" => Self::RhamnusCathartica,
            "3970" => Self::RhamnusImeretinus,
            "3980" => Self::RhodotyposScandens,
            "3990" => Self::RhusHirta,
            "4000" => Self::RibesAureum,
            "4010" => Self::RibesSanguineum,
            "4020" => Self::RobiniaPseudoacacia,
            "4030" => Self::RosaCanina,
            "4040" => Self::RosaSpinosissima,
            "4050" => Self::RubusFruticosus,
            "4060" => Self::SalixAlba,
            "4070" => Self::SalixAlbaTristis,
            "4080" => Self::SalixAurita,
            "4090" => Self::SalixBabylonica,
            "4100" => Self::SalixCaprea,
            "4110" => Self::SalixCapreaKilmarnock,
            "4120" => Self::SalixCinerea,
            "4130" => Self::SalixFragilis,
            "4140" => Self::SalixMatsudanaTortuosa,
            "4150" => Self::SalixViminalis,
            "4160" => Self::SambucusNigra,
            "4170" => Self::SambucusRacemosa,
            "4180" => Self::SciadopitysVerticillata,
            "4190" => Self::SequoiaSempervirens,
            "4200" => Self::SequoiadendronGiganteum,
            "4210" => Self::ShepherdiaArgentea,
            "4220" => Self::SophoraJaponica,
            "4230" => Self::SorbusAria,
            "4240" => Self::SRbusAucupRia,
            "4250" => Self::SorbusDomestica,
            "4260" => Self::SorbusIntermedia,
            "4270" => Self::SorbusTorminalis,
            "4280" => Self::SpiraeaXBillardii,
            "4290" => Self::SpiraeaXVanhouttei,
            "4300" => Self::StaphyleaPinnata,
            "4310" => Self::StranvaesiaDavidiana,
            "4320" => Self::SymphoricarposAlbus,
            "4330" => Self::SyringaReflexa,
            "4340" => Self::SyringaVulgaris,
            "4350" => Self::TamarixParviflora,
            "4360" => Self::TaxodiumDistichum,
            "4370" => Self::TaxusBaccata,
            "4380" => Self::ThujaOccidentalis,
            "4390" => Self::ThujaPlicata,
            "4400" => Self::ThujopsisDolabrata,
            "4410" => Self::TLiaCordTa,
            "4420" => Self::TiliaPlatyphyllos,
            "4430" => Self::TiliaTomentosa,
            "4440" => Self::TsugaCanadensis,
            "4450" => Self::UlexEuropaeus,
            "4460" => Self::LmusGlBra,
            "4470" => Self::UlmusLaevis,
            "4480" => Self::LmusMNor,
            "4490" => Self::UlmusPumila,
            "4500" => Self::ViburnumFarreri,
            "4510" => Self::ViburnumLantana,
            "4520" => Self::ViburnumLentago,
            "4530" => Self::ViburnumOpulus,
            "4540" => Self::ViburnumRhytidophyllum,
            "4550" => Self::ViburnumTinus,
            "4560" => Self::ViburnumXBodnantense,
            "4570" => Self::ViscumAlbum,
            "4580" => Self::VitisCoignetiae,
            "4590" => Self::WeigelaFlorida,
            "4600" => Self::WisteriaSinensis,
            "4610" => Self::ZelkovaSerrata,
            "4620" => Self::Acer4620,
            "4630" => Self::ActinidiaLind,
            "4640" => Self::AeschynanthusJack,
            "4650" => Self::Ageratum,
            "4660" => Self::AgrostemmaGithago,
            "4670" => Self::Agrostis,
            "4680" => Self::AlliumCepa,
            "4690" => Self::AlliumFistulosum,
            "4700" => Self::AlliumPorrum,
            "4710" => Self::AlliumSchoenoprasum,
            "4720" => Self::Aloe,
            "4730" => Self::AlonsoaMeridionalisFOKuntze,
            "4740" => Self::AlopecurusPratensis,
            "4750" => Self::Alstroemeria,
            "4760" => Self::AmaranthusBlitoidesSWatson,
            "4770" => Self::AmaranthusCruentus,
            "4780" => Self::AnigozanthosLabil,
            "4790" => Self::AnthriscusCerefoliumHoffm,
            "4800" => Self::AnthuriumSchott,
            "4810" => Self::Antirrhinum,
            "4820" => Self::ApiumGraveolens,
            "4830" => Self::Arctium,
            "4840" => Self::ArgyranthemumFrutescensSchultzBip,
            "4850" => Self::ArnicaMontana,
            "4860" => Self::AroniaMedik,
            "4870" => Self::ArrhenatherumElatiusPBeauvExJSEtKBPresl,
            "4880" => Self::AsparagusOfficinalis,
            "4890" => Self::Aster,
            "4900" => Self::AubrietaAdans,
            "4910" => Self::AvenaSativa4910,
            "4920" => Self::AvenaSativa4920,
            "4930" => Self::BegoniaXHiemalisFotsch,
            "4940" => Self::BegoniaXTuberhybridaVoss,
            "4950" => Self::BegoniaSemperflorensHybriden,
            "4960" => Self::BetaVulgarisVarAltissimaDLl,
            "4970" => Self::BetaVulgarisVarConditivaAlef,
            "4980" => Self::BetaVulgarisVarCrassaMansf,
            "4990" => Self::BetaVulgarisVarVulgaris,
            "5000" => Self::BidensFerulifoliaJacqDc,
            "5010" => Self::BrachyscomeCass,
            "5020" => Self::BrassicaJunceaCzernjEtCosson,
            "5030" => Self::BrassicaNapusPartim5030,
            "5040" => Self::BrassicaNapusPartim5040,
            "5050" => Self::BrassicaNapusVarNapobrassicaRchb,
            "5060" => Self::BrassicaOleraceaConvarAcephalaDcAlefVarGongylodes,
            "5070" => Self::BrassicaOleraceaConvarAcephalaDcAlefVarMedullosaThelUndVarViridis,
            "5080" => Self::BrassicaOleraceaConvarAcephalaDcAlefVarSabellica,
            "5090" => Self::BrassicaOleraceaConvarBotrytisAlefVarBotrytis,
            "5100" => Self::BrassicaOleraceaConvarBotrytisAlefVarCymosaDuch,
            "5110" => Self::BrassicaOleraceaConvarCapitataAlefVarAlbaDc,
            "5120" => Self::BrassicaOleraceaConvarCapitataAlefVarRubraDc,
            "5130" => Self::BrassicaOleraceaConvarCapitataAlefVarSabauda,
            "5140" => Self::BrassicaOleraceaConvarOleraceaVarGemmiferaDc,
            "5150" => Self::BrassicaRapaVarRapa5150,
            "5160" => Self::BrassicaRapaVarRapa5160,
            "5170" => Self::BrassicaRapaVarSilvestrisLamBriggs5170,
            "5180" => Self::BrassicaRapaVarSilvestrisLamBriggs5180,
            "5190" => Self::Bromus,
            "5200" => Self::BrunneraMacrophyllaAdamsJohnst,
            "5210" => Self::Calceolaria,
            "5220" => Self::CallunaVulgarisHull,
            "5230" => Self::CamelinaSativaCrantz,
            "5240" => Self::CannabisSativa,
            "5250" => Self::CapsicumAnnuum,
            "5260" => Self::Carex,
            "5270" => Self::CarthamusTinctorius,
            "5280" => Self::Celosia,
            "5290" => Self::ChamomillaRecutitaRauschert,
            "5300" => Self::CichoriumEndivia,
            "5310" => Self::Clematis5310,
            "5320" => Self::ConvallariaMajalis,
            "5330" => Self::CoronillaVaria,
            "5340" => Self::Corylus,
            "5350" => Self::CrassulaSchmidtiiRegel,
            "5360" => Self::CucumisSativus,
            "5370" => Self::Cucurbita,
            "5380" => Self::CucurbitaPepo,
            "5390" => Self::CupheaPBr,
            "5400" => Self::CydoniaOblongaMil,
            "5410" => Self::CynaraCardunculus,
            "5420" => Self::CynaraScolymus,
            "5430" => Self::DaboeciaCantabricaHudsKKoch,
            "5440" => Self::Dactylis,
            "5450" => Self::DahliaCav,
            "5460" => Self::DaucusCarota5460,
            "5470" => Self::DaucusCarota5470,
            "5480" => Self::DendranthemaXGrandiflorumRamatKitam,
            "5490" => Self::DeschampsiaCespitosaPBeauv,
            "5500" => Self::Dianthus,
            "5510" => Self::Digitalis,
            "5520" => Self::DracocephalumMoldavica,
            "5530" => Self::EchinodorusCRichExEngelm,
            "5540" => Self::Erica,
            "5550" => Self::EuonymusFortuneiTurczHandMazz,
            "5560" => Self::EuphorbiaFulgensKarwExKlotzsch,
            "5570" => Self::EuphorbiaMiliiDesMouVarMilii,
            "5580" => Self::EuphorbiaPulcherrimaWilldExKlotzsch,
            "5590" => Self::FagopyrumMil,
            "5600" => Self::FestucaArundinaceaSchreber,
            "5610" => Self::FestucaOvinaSensuLato,
            "5620" => Self::FestucaPratensisHudson,
            "5630" => Self::FestucaRubraSensuLato,
            "5640" => Self::FicusBenjamina,
            "5650" => Self::FicusCarica5650,
            "5660" => Self::FoeniculumVulgareMil5660,
            "5670" => Self::FoeniculumVulgareMil5670,
            "5680" => Self::ForsythiaVahl,
            "5690" => Self::Fragaria,
            "5700" => Self::Fuchsia5700,
            "5710" => Self::GazaniaHybriden,
            "5720" => Self::Gentiana,
            "5730" => Self::Gerbera5730,
            "5740" => Self::GinkgoBiloba,
            "5750" => Self::GlycineMaxMerr,
            "5760" => Self::HebeCommExJuss,
            "5770" => Self::HelianthusAnnuus,
            "5780" => Self::HelianthusTuberosus,
            "5790" => Self::HelichrysumItalicumRothGussone,
            "5800" => Self::HeliotropiumArborescens,
            "5810" => Self::Helleborus5810,
            "5820" => Self::Hippophae,
            "5830" => Self::HordeumVulgareSensuLato5830,
            "5840" => Self::HordeumVulgareSensuLato5840,
            "5850" => Self::HumulusLupulus,
            "5860" => Self::Hydrangea5860,
            "5870" => Self::HypericumAndrosaemum,
            "5880" => Self::HypericumPerforatum,
            "5890" => Self::HyssopusOfficinalis,
            "5900" => Self::Ilex,
            "5910" => Self::Impatiens,
            "5920" => Self::ImpatiensWallerianaHybriden,
            "5930" => Self::JuglansHybriden,
            "5940" => Self::KalanchoeAdans,
            "5950" => Self::LactucaSativa5950,
            "5960" => Self::LactucaSativa5960,
            "5970" => Self::LeontopodiumAlpinumCass,
            "5980" => Self::LeucanthemumXSuperbumJWIngramBergmansExKent,
            "5990" => Self::Lilium,
            "6000" => Self::LimoniumMil,
            "6010" => Self::LinumUsitatissimum,
            "6020" => Self::LiquidambarStyraciflua6020,
            "6030" => Self::Lobelia,
            "6040" => Self::LoliumPartim,
            "6050" => Self::LoliumMultiflorumLam,
            "6060" => Self::LoliumPerenne,
            "6070" => Self::LoliumXBoucheanumKunth,
            "6080" => Self::LoniceraNitidaWils,
            "6090" => Self::LotusCorniculatus,
            "6100" => Self::LupinusLuteus,
            "6110" => Self::LupinusAlbus,
            "6120" => Self::LupinusAngustifolius,
            "6130" => Self::LupinusMutabilis,
            "6140" => Self::LupinusNanusDouglas,
            "6150" => Self::LycopersiconLycopersicumKarstenExFarw,
            "6160" => Self::MalusMil6160,
            "6170" => Self::MalusMil6170,
            "6180" => Self::MalusMil6180,
            "6190" => Self::MalvaVerticillata,
            "6200" => Self::MedicagoLupulina,
            "6210" => Self::MedicagoSativa,
            "6220" => Self::MelissaOfficinalis,
            "6230" => Self::Nicotiana,
            "6240" => Self::OcimumBasilicum,
            "6250" => Self::OnobrychisViciifoliaScop,
            "6260" => Self::Orchidaceae,
            "6270" => Self::OriganumMajorana,
            "6280" => Self::OriganumVulgare,
            "6290" => Self::PelargoniumLhRitExAit,
            "6300" => Self::PelargoniumGrandiflorumHybriden,
            "6310" => Self::PetroselinumCrispumMillerNymanExAWHill6310,
            "6320" => Self::PetroselinumCrispumMillerNymanExAWHill6320,
            "6330" => Self::PetuniaJuss,
            "6340" => Self::PhaceliaJuss,
            "6350" => Self::PhalarisArundinacea,
            "6360" => Self::PhaseolusCoccineus,
            "6370" => Self::PhaseolusVulgaris6370,
            "6380" => Self::PhaseolusVulgaris6380,
            "6390" => Self::Phleum,
            "6400" => Self::PhysocarpusCambessMaxim,
            "6410" => Self::PiceaADietr,
            "6420" => Self::Pinus6420,
            "6430" => Self::PisumSativumPartim6430,
            "6440" => Self::PisumSativumPartim6440,
            "6450" => Self::PisumSativumPartim6450,
            "6460" => Self::PisumSativumPartim6460,
            "6470" => Self::Poa,
            "6480" => Self::PoaPratensis,
            "6490" => Self::Populus6490,
            "6500" => Self::Prunus6500,
            "6510" => Self::Prunus6510,
            "6520" => Self::PrunusAvium6520,
            "6530" => Self::PrunusCerasus,
            "6540" => Self::PrunusDomestica6540,
            "6550" => Self::PrunusPersicaBatsch,
            "6560" => Self::PrunusSpinosa6560,
            "6570" => Self::PyracanthaMJRoem,
            "6580" => Self::Pyrus6580,
            "6590" => Self::Pyrus6590,
            "6600" => Self::Quercus6600,
            "6610" => Self::Raphanobrassica,
            "6620" => Self::RaphanusSativusVarNigerMillerSKerner,
            "6630" => Self::RaphanusSativusVarOleiformisPers,
            "6640" => Self::RaphanusSativusVarSativus,
            "6650" => Self::RehmanniaLiboschExFischEtCAMey,
            "6660" => Self::Rhododendron6660,
            "6670" => Self::RhododendronSimsiiPlanch,
            "6680" => Self::Ribes6680,
            "6690" => Self::Ribes6690,
            "6700" => Self::RibesNigrum,
            "6710" => Self::RibesXNidigrolariaREtABauer,
            "6720" => Self::Rosa,
            "6730" => Self::Rubus6730,
            "6740" => Self::Rubus6740,
            "6750" => Self::SaintpauliaHWend,
            "6760" => Self::Salix6760,
            "6770" => Self::SanvitaliaLam,
            "6780" => Self::SaturejaHortensis,
            "6790" => Self::ScorzoneraHispanica,
            "6800" => Self::Secale6800,
            "6810" => Self::Secale6810,
            "6820" => Self::SilybumMarianumGaertn,
            "6830" => Self::SinapisAlba,
            "6840" => Self::SinningiaNees,
            "6850" => Self::Solanum,
            "6860" => Self::SolanumTuberosum,
            "6870" => Self::SpinaciaOleracea,
            "6880" => Self::StreptocarpusLind,
            "6890" => Self::SuteraRoth,
            "6900" => Self::SymphoricarposDuham,
            "6910" => Self::Syringa,
            "6920" => Self::Tagetes,
            "6930" => Self::TanacetumPartheniumSchultzBip,
            "6940" => Self::Tilia,
            "6950" => Self::TrifoliumAlexandrinum,
            "6960" => Self::TrifoliumHybridum,
            "6970" => Self::TrifoliumIncarnatum,
            "6980" => Self::TrifoliumPratense,
            "6990" => Self::TrifoliumRepens,
            "7000" => Self::TrifoliumResupinatum,
            "7010" => Self::TrisetumFlavescensPBeauv,
            "7020" => Self::TriticumAestivumEmendFioriEtPao7020,
            "7030" => Self::TriticumAestivumEmendFioriEtPao7030,
            "7040" => Self::TriticumDurumDesf,
            "7050" => Self::TriticumMonococcum,
            "7060" => Self::TriticumSpelta,
            "7070" => Self::Tulipa,
            "7080" => Self::TussilagoFarfara,
            "7090" => Self::Ulmus,
            "7100" => Self::Urtica,
            "7110" => Self::Vaccinium,
            "7120" => Self::ValerianaOfficinalis,
            "7130" => Self::ValerianellaLocustaLaterr,
            "7140" => Self::Vallisneria,
            "7150" => Self::ViciaPartim,
            "7160" => Self::ViciaFabaPartim7160,
            "7170" => Self::ViciaFabaPartim7170,
            "7180" => Self::ViciaSativa,
            "7190" => Self::VincaMinor,
            "7200" => Self::VitexAgnusCastus,
            "7210" => Self::Vitis,
            "7220" => Self::VitisVinifera,
            "7230" => Self::VrieseaSplendensBrongnLem,
            "7240" => Self::ZantedeschiaSpreng,
            "7250" => Self::ZeaMays,
            "7260" => Self::XFestulolium,
            "7270" => Self::XTriticosecaleWittm7270,
            "7280" => Self::XTriticosecaleWittm7280,
            "9999" => Self::Unknown,
            other => Self::Other(other.to_string()),
        }
    }

    fn to_code_value(&self) -> &str {
        match self {
            Self::Picea => "1000",
            Self::Pinus1010 => "1010",
            Self::Larix => "1020",
            Self::Quercus1030 => "1030",
            Self::Fagus => "1040",
            Self::Betula => "1050",
            Self::Alnus => "1060",
            Self::Populus1070 => "1070",
            Self::Salix1080 => "1080",
            Self::Acer1090 => "1090",
            Self::Fraxinus => "1100",
            Self::Arabis => "1110",
            Self::GaleobdolonLuteum => "1120",
            Self::CampanulaPoscharskyana => "1130",
            Self::GaliumOdoratum => "1140",
            Self::AlliumUrsinum => "1150",
            Self::Helleborus1160 => "1160",
            Self::Alchemilla => "1170",
            Self::Iris => "1180",
            Self::Begonia => "1190",
            Self::RanunculusAsiaticus => "1200",
            Self::GeraniumMacrorrhizumIngwersen => "1210",
            Self::PelargonieBurcDouble => "1220",
            Self::Euphorbia => "1230",
            Self::Aqulilegia => "1240",
            Self::SymphytumOfficinale => "1250",
            Self::SedumSpectabileUndSedumTelphium => "1260",
            Self::Centaurea => "1270",
            Self::CentaureaCysanus => "1280",
            Self::LychnisCoronaria => "1290",
            Self::Physalis => "1300",
            Self::CoreopsisVerticillata => "1310",
            Self::Calendula => "1320",
            Self::PhloxPaniculata => "1330",
            Self::DianthusBarbatus => "1340",
            Self::Hemerocallis => "1350",
            Self::HemerocallisFlava => "1360",
            Self::Lythrum => "1370",
            Self::Lysmachia => "1380",
            Self::AsterNovae => "1390",
            Self::CardiocrinumGiganteum => "1400",
            Self::Delphinium => "1410",
            Self::Pteridium => "1420",
            Self::GymnocarpiumDryopteris => "1430",
            Self::MatteucciaStruthiopteris => "1440",
            Self::MagnoliaElisabeth => "1450",
            Self::Hibiskus => "1460",
            Self::Hydrangea1470 => "1470",
            Self::CotinusCoggygria1480 => "1480",
            Self::EuonymusEuropea => "1490",
            Self::Rhododendron1500 => "1500",
            Self::Pontederia => "1510",
            Self::Clematis1520 => "1520",
            Self::Tropaeolum => "1530",
            Self::ViciaLathyrus => "1540",
            Self::Plumbago => "1550",
            Self::Zantedeschia => "1560",
            Self::Fuchsia1570 => "1570",
            Self::Gerbera1580 => "1580",
            Self::Nopalxochia => "1590",
            Self::Hydrangea1600 => "1600",
            Self::Cassia => "1610",
            Self::Cistus => "1620",
            Self::AbienusFestuschristus => "1630",
            Self::AbiesAlba => "1640",
            Self::AbiesCephalonica => "1650",
            Self::AbiesConcolor => "1660",
            Self::AbiesGrandis => "1670",
            Self::AbiesHomolepsis => "1680",
            Self::AbiesKoreana => "1690",
            Self::AbiesLasiocarpa => "1700",
            Self::AbiesNordmanniana => "1710",
            Self::AbiesPinsapo => "1720",
            Self::AbiesProcera => "1730",
            Self::AbiesProceraGlauca => "1740",
            Self::AbiesVeitchii => "1750",
            Self::AcerCampStre => "1760",
            Self::AcerCapillipes => "1770",
            Self::AcerCappadocicum => "1780",
            Self::AcerCircinatum => "1790",
            Self::AcerDavidii => "1800",
            Self::AcerGinnalaMaxim => "1810",
            Self::AcerGrosserii => "1820",
            Self::AcerMonspessulanum => "1830",
            Self::AcerNegundo => "1840",
            Self::AcerPalmatum => "1850",
            Self::AcerPlatanoides => "1860",
            Self::AcerPlatanoidesCrimsonKing => "1870",
            Self::AcerPseudoplatanus => "1880",
            Self::AcerRubrum => "1890",
            Self::AcerSaccharinum => "1900",
            Self::AcerSaccharumMarsch => "1910",
            Self::AcerTartaricum => "1920",
            Self::AesculusHippocStanum => "1930",
            Self::AesculusXCarnea => "1940",
            Self::AfzeliaAfricana => "1950",
            Self::AilanthusAltissima => "1960",
            Self::AlnusCordata => "1970",
            Self::AlnusGlutinosa => "1980",
            Self::AlnusIncNa => "1990",
            Self::AlnusViridis => "2000",
            Self::AmelNchierOvLis => "2010",
            Self::AnacardiumOccidentale => "2020",
            Self::AraliaElata => "2030",
            Self::AraucariaAraucana => "2040",
            Self::AucubaJaponica => "2050",
            Self::BerberisJulianae => "2060",
            Self::BerberisThunbergii => "2070",
            Self::BetulaAlnoides => "2080",
            Self::BetulaCostata => "2090",
            Self::BetulaDavurica => "2100",
            Self::BetulaErmanii => "2110",
            Self::BetulaPapyrifera => "2120",
            Self::BTulaPNdula => "2130",
            Self::BetulaPubescens => "2140",
            Self::BroussonetiaPapyrifera => "2150",
            Self::BuddlejaDavidii => "2160",
            Self::ButyrospermumParkii => "2170",
            Self::BuxusSempervirens => "2180",
            Self::CalocedrusDecurrens => "2190",
            Self::CalocedrusDecurrensAureovariegata => "2200",
            Self::CalycanthusFloridus => "2210",
            Self::CampsisRadicans => "2220",
            Self::CaraganaArborescens => "2230",
            Self::CarpNusBTulus => "2240",
            Self::CassiaSiberiana => "2250",
            Self::CastanASatVa => "2260",
            Self::CatalpaBignonioides => "2270",
            Self::CedrelaSinensis => "2280",
            Self::CedrusAtlantica => "2290",
            Self::CedrusAtlanticaGlauca => "2300",
            Self::CedrusDeodara => "2310",
            Self::CedrusDeodaraVarPaktia => "2320",
            Self::CedrusLibani => "2330",
            Self::CeltisOccidentalis => "2340",
            Self::CercisSiliquastrum => "2350",
            Self::ChaenomelesJaponica => "2360",
            Self::ChamaecyparisLawsonia => "2370",
            Self::ChamaecyparisNootkatensis => "2380",
            Self::ChionanthusVirginicus => "2390",
            Self::CladrastisLutea => "2400",
            Self::ClematisMontana => "2410",
            Self::ClematisVitalba => "2420",
            Self::ColuteaArborescens => "2430",
            Self::CornusAlba => "2440",
            Self::CornusFlorida => "2450",
            Self::CornusMas => "2460",
            Self::CornusSanguinea => "2470",
            Self::CRylusAvellNa => "2480",
            Self::CorylusAvellanaContorta => "2490",
            Self::CRylusColRna => "2500",
            Self::CorylusMaxima => "2510",
            Self::CotinusCoggygria2520 => "2520",
            Self::CotoneasterFrigidus => "2530",
            Self::CrataegusLaevigata => "2540",
            Self::CrataegusLaevigataPaulsScarlet => "2550",
            Self::CrataegusLavalleiCarrierei => "2560",
            Self::CrataegusMonogyna => "2570",
            Self::CryptomeriaJaponica => "2580",
            Self::CupressusArizonica => "2590",
            Self::CupressusSempervirens => "2600",
            Self::DavidiaInvolucrata => "2610",
            Self::DelonixRegia => "2620",
            Self::DeutziaScabra => "2630",
            Self::DracaenaDraco => "2640",
            Self::ElaeagnusAngustifolia => "2650",
            Self::ElaeagnusUmbellata => "2660",
            Self::EuonymusAlatus => "2670",
            Self::EuonymusEuropaeus => "2680",
            Self::EuonymusPlanipes => "2690",
            Self::FagusOrientalis => "2700",
            Self::FagusSylvatica => "2710",
            Self::FagusSylvaticaPendula => "2720",
            Self::FGusSylvTicaPurpurA => "2730",
            Self::FicusCarica2740 => "2740",
            Self::ForsythiaXIntermedia => "2750",
            Self::FrangulaAlnus => "2760",
            Self::FraxNusExcLsior => "2770",
            Self::FraxinusLatifolia => "2780",
            Self::FraxinusOrnus => "2790",
            Self::FraxinusPaxiana => "2800",
            Self::GinkgoBilobaL => "2810",
            Self::GleditsiaTriacanthos => "2820",
            Self::HalesiaCarolina => "2830",
            Self::HamamelisVirginiana => "2840",
            Self::HamamelisXIntermedia => "2850",
            Self::HederaHelix => "2860",
            Self::HibiscusSyriacus => "2870",
            Self::HippophaeRhamnoides => "2880",
            Self::IlexAquifolium => "2890",
            Self::JasminumNudiflorum => "2900",
            Self::JuglansNigra => "2910",
            Self::JuglansRegia => "2920",
            Self::JuniperusCommunis => "2930",
            Self::JuniperusSabina => "2940",
            Self::KerriaJaponicaPleniflora => "2950",
            Self::KhayaSenegalensis => "2960",
            Self::KoelreuteriaPaniculata => "2970",
            Self::KolkwitziaAmabilis => "2980",
            Self::LaburnumAlpinum => "2990",
            Self::LaburnumAnagyroides => "3000",
            Self::LarixDecidua => "3010",
            Self::LarixKaempferi => "3020",
            Self::LigustrumVulgare => "3030",
            Self::LiquidambarOrientalis => "3040",
            Self::LiquidambarStyraciflua3050 => "3050",
            Self::LiriodendronTulipifera => "3060",
            Self::LoniceraMaackii => "3070",
            Self::LoniceraTartarica => "3080",
            Self::LoniceraXHeckrottii => "3090",
            Self::LoniceraXylosteum => "3100",
            Self::MagnoliaXSoulangiana => "3110",
            Self::MahoniaAquifolium => "3120",
            Self::MalusFloribunda => "3130",
            Self::MLusSylvStris => "3140",
            Self::MalusToringoides => "3150",
            Self::MespilusGermanica => "3160",
            Self::MetasequoiaGlyptostroboides => "3170",
            Self::OstryaCarpinifolia => "3180",
            Self::ParrotiaPersica => "3190",
            Self::ParthenocissusQuinquefolia => "3200",
            Self::ParthenocissusTricuspidata => "3210",
            Self::PaulowniaTomentosa => "3220",
            Self::PhiladelphusCoronarius => "3230",
            Self::PiceaAbies => "3240",
            Self::PiceaAbiesInversa => "3250",
            Self::PiceaAsperata => "3260",
            Self::PiceaEngelmanii => "3270",
            Self::PiceaGlauca => "3280",
            Self::PiceaGlaucaConica => "3290",
            Self::PiceaOmorika => "3300",
            Self::PiceaOrientalis => "3310",
            Self::PiceaPolita => "3320",
            Self::PiceaPungensGlauca => "3330",
            Self::PiceaSitchensis => "3340",
            Self::PinusAristata => "3350",
            Self::PinusArmandii => "3360",
            Self::PinusCembra => "3370",
            Self::PinusContorta => "3380",
            Self::PinusHeldreichii => "3390",
            Self::PinusJeffreyi => "3400",
            Self::PinusKoraiensis => "3410",
            Self::PinusLeucodermis => "3420",
            Self::PinusMugo => "3430",
            Self::PinusNigra => "3440",
            Self::PinusNigraVar3450 => "3450",
            Self::PinusNigraVar3460 => "3460",
            Self::PinusParviflora => "3470",
            Self::PinusPeuce => "3480",
            Self::PinusPonderosa => "3490",
            Self::PinusStrobus => "3500",
            Self::PinusSylvestris => "3510",
            Self::PinusThunbergii => "3520",
            Self::PinusWallichiana => "3530",
            Self::PlatanusAcerifolia => "3540",
            Self::PlatanusOrientalis => "3550",
            Self::PlatycladusOrientalis => "3560",
            Self::PopulusAlba => "3570",
            Self::PopulusNigra => "3580",
            Self::PopulusSimonii => "3590",
            Self::PopulusTremula => "3600",
            Self::PopulusXCanadensis => "3610",
            Self::PopulusXCanescens => "3620",
            Self::PrunusAvium3630 => "3630",
            Self::PrunusCerasiferaNigra => "3640",
            Self::PrunusDomestica3650 => "3650",
            Self::PrunusDomesticaSsp => "3660",
            Self::PrunusDulcis => "3670",
            Self::PrunusLaurocerasus => "3680",
            Self::PrNusPDus => "3690",
            Self::PrunusSargentii => "3700",
            Self::PrunusSerotina => "3710",
            Self::PrunusSerrulata => "3720",
            Self::PrunusSpinosa3730 => "3730",
            Self::PrunusSubhirtella => "3740",
            Self::PseudotsugaMenziesii => "3750",
            Self::PteleaTrifoliata => "3760",
            Self::PterocaryaFraxinifolia => "3770",
            Self::PterocaryaStenoptera => "3780",
            Self::PyracanthaCoccinea => "3790",
            Self::PRusPyrSter => "3800",
            Self::QuercusAcutissima => "3810",
            Self::QuercusCerris => "3820",
            Self::QuercusCoccinea => "3830",
            Self::QuercusFrainetto => "3840",
            Self::QuercusIlex => "3850",
            Self::QuercusLibani => "3860",
            Self::QuercusPalustris => "3870",
            Self::QuercusPetraea => "3880",
            Self::QuercusPrinus => "3890",
            Self::QuercusPubescens => "3900",
            Self::QuercusRobur => "3910",
            Self::QuercusRubra => "3920",
            Self::QuercusSuber => "3930",
            Self::QuercusXHispanicaLucombeana => "3940",
            Self::QuercusXTurneri => "3950",
            Self::RhamnusCathartica => "3960",
            Self::RhamnusImeretinus => "3970",
            Self::RhodotyposScandens => "3980",
            Self::RhusHirta => "3990",
            Self::RibesAureum => "4000",
            Self::RibesSanguineum => "4010",
            Self::RobiniaPseudoacacia => "4020",
            Self::RosaCanina => "4030",
            Self::RosaSpinosissima => "4040",
            Self::RubusFruticosus => "4050",
            Self::SalixAlba => "4060",
            Self::SalixAlbaTristis => "4070",
            Self::SalixAurita => "4080",
            Self::SalixBabylonica => "4090",
            Self::SalixCaprea => "4100",
            Self::SalixCapreaKilmarnock => "4110",
            Self::SalixCinerea => "4120",
            Self::SalixFragilis => "4130",
            Self::SalixMatsudanaTortuosa => "4140",
            Self::SalixViminalis => "4150",
            Self::SambucusNigra => "4160",
            Self::SambucusRacemosa => "4170",
            Self::SciadopitysVerticillata => "4180",
            Self::SequoiaSempervirens => "4190",
            Self::SequoiadendronGiganteum => "4200",
            Self::ShepherdiaArgentea => "4210",
            Self::SophoraJaponica => "4220",
            Self::SorbusAria => "4230",
            Self::SRbusAucupRia => "4240",
            Self::SorbusDomestica => "4250",
            Self::SorbusIntermedia => "4260",
            Self::SorbusTorminalis => "4270",
            Self::SpiraeaXBillardii => "4280",
            Self::SpiraeaXVanhouttei => "4290",
            Self::StaphyleaPinnata => "4300",
            Self::StranvaesiaDavidiana => "4310",
            Self::SymphoricarposAlbus => "4320",
            Self::SyringaReflexa => "4330",
            Self::SyringaVulgaris => "4340",
            Self::TamarixParviflora => "4350",
            Self::TaxodiumDistichum => "4360",
            Self::TaxusBaccata => "4370",
            Self::ThujaOccidentalis => "4380",
            Self::ThujaPlicata => "4390",
            Self::ThujopsisDolabrata => "4400",
            Self::TLiaCordTa => "4410",
            Self::TiliaPlatyphyllos => "4420",
            Self::TiliaTomentosa => "4430",
            Self::TsugaCanadensis => "4440",
            Self::UlexEuropaeus => "4450",
            Self::LmusGlBra => "4460",
            Self::UlmusLaevis => "4470",
            Self::LmusMNor => "4480",
            Self::UlmusPumila => "4490",
            Self::ViburnumFarreri => "4500",
            Self::ViburnumLantana => "4510",
            Self::ViburnumLentago => "4520",
            Self::ViburnumOpulus => "4530",
            Self::ViburnumRhytidophyllum => "4540",
            Self::ViburnumTinus => "4550",
            Self::ViburnumXBodnantense => "4560",
            Self::ViscumAlbum => "4570",
            Self::VitisCoignetiae => "4580",
            Self::WeigelaFlorida => "4590",
            Self::WisteriaSinensis => "4600",
            Self::ZelkovaSerrata => "4610",
            Self::Acer4620 => "4620",
            Self::ActinidiaLind => "4630",
            Self::AeschynanthusJack => "4640",
            Self::Ageratum => "4650",
            Self::AgrostemmaGithago => "4660",
            Self::Agrostis => "4670",
            Self::AlliumCepa => "4680",
            Self::AlliumFistulosum => "4690",
            Self::AlliumPorrum => "4700",
            Self::AlliumSchoenoprasum => "4710",
            Self::Aloe => "4720",
            Self::AlonsoaMeridionalisFOKuntze => "4730",
            Self::AlopecurusPratensis => "4740",
            Self::Alstroemeria => "4750",
            Self::AmaranthusBlitoidesSWatson => "4760",
            Self::AmaranthusCruentus => "4770",
            Self::AnigozanthosLabil => "4780",
            Self::AnthriscusCerefoliumHoffm => "4790",
            Self::AnthuriumSchott => "4800",
            Self::Antirrhinum => "4810",
            Self::ApiumGraveolens => "4820",
            Self::Arctium => "4830",
            Self::ArgyranthemumFrutescensSchultzBip => "4840",
            Self::ArnicaMontana => "4850",
            Self::AroniaMedik => "4860",
            Self::ArrhenatherumElatiusPBeauvExJSEtKBPresl => "4870",
            Self::AsparagusOfficinalis => "4880",
            Self::Aster => "4890",
            Self::AubrietaAdans => "4900",
            Self::AvenaSativa4910 => "4910",
            Self::AvenaSativa4920 => "4920",
            Self::BegoniaXHiemalisFotsch => "4930",
            Self::BegoniaXTuberhybridaVoss => "4940",
            Self::BegoniaSemperflorensHybriden => "4950",
            Self::BetaVulgarisVarAltissimaDLl => "4960",
            Self::BetaVulgarisVarConditivaAlef => "4970",
            Self::BetaVulgarisVarCrassaMansf => "4980",
            Self::BetaVulgarisVarVulgaris => "4990",
            Self::BidensFerulifoliaJacqDc => "5000",
            Self::BrachyscomeCass => "5010",
            Self::BrassicaJunceaCzernjEtCosson => "5020",
            Self::BrassicaNapusPartim5030 => "5030",
            Self::BrassicaNapusPartim5040 => "5040",
            Self::BrassicaNapusVarNapobrassicaRchb => "5050",
            Self::BrassicaOleraceaConvarAcephalaDcAlefVarGongylodes => "5060",
            Self::BrassicaOleraceaConvarAcephalaDcAlefVarMedullosaThelUndVarViridis => "5070",
            Self::BrassicaOleraceaConvarAcephalaDcAlefVarSabellica => "5080",
            Self::BrassicaOleraceaConvarBotrytisAlefVarBotrytis => "5090",
            Self::BrassicaOleraceaConvarBotrytisAlefVarCymosaDuch => "5100",
            Self::BrassicaOleraceaConvarCapitataAlefVarAlbaDc => "5110",
            Self::BrassicaOleraceaConvarCapitataAlefVarRubraDc => "5120",
            Self::BrassicaOleraceaConvarCapitataAlefVarSabauda => "5130",
            Self::BrassicaOleraceaConvarOleraceaVarGemmiferaDc => "5140",
            Self::BrassicaRapaVarRapa5150 => "5150",
            Self::BrassicaRapaVarRapa5160 => "5160",
            Self::BrassicaRapaVarSilvestrisLamBriggs5170 => "5170",
            Self::BrassicaRapaVarSilvestrisLamBriggs5180 => "5180",
            Self::Bromus => "5190",
            Self::BrunneraMacrophyllaAdamsJohnst => "5200",
            Self::Calceolaria => "5210",
            Self::CallunaVulgarisHull => "5220",
            Self::CamelinaSativaCrantz => "5230",
            Self::CannabisSativa => "5240",
            Self::CapsicumAnnuum => "5250",
            Self::Carex => "5260",
            Self::CarthamusTinctorius => "5270",
            Self::Celosia => "5280",
            Self::ChamomillaRecutitaRauschert => "5290",
            Self::CichoriumEndivia => "5300",
            Self::Clematis5310 => "5310",
            Self::ConvallariaMajalis => "5320",
            Self::CoronillaVaria => "5330",
            Self::Corylus => "5340",
            Self::CrassulaSchmidtiiRegel => "5350",
            Self::CucumisSativus => "5360",
            Self::Cucurbita => "5370",
            Self::CucurbitaPepo => "5380",
            Self::CupheaPBr => "5390",
            Self::CydoniaOblongaMil => "5400",
            Self::CynaraCardunculus => "5410",
            Self::CynaraScolymus => "5420",
            Self::DaboeciaCantabricaHudsKKoch => "5430",
            Self::Dactylis => "5440",
            Self::DahliaCav => "5450",
            Self::DaucusCarota5460 => "5460",
            Self::DaucusCarota5470 => "5470",
            Self::DendranthemaXGrandiflorumRamatKitam => "5480",
            Self::DeschampsiaCespitosaPBeauv => "5490",
            Self::Dianthus => "5500",
            Self::Digitalis => "5510",
            Self::DracocephalumMoldavica => "5520",
            Self::EchinodorusCRichExEngelm => "5530",
            Self::Erica => "5540",
            Self::EuonymusFortuneiTurczHandMazz => "5550",
            Self::EuphorbiaFulgensKarwExKlotzsch => "5560",
            Self::EuphorbiaMiliiDesMouVarMilii => "5570",
            Self::EuphorbiaPulcherrimaWilldExKlotzsch => "5580",
            Self::FagopyrumMil => "5590",
            Self::FestucaArundinaceaSchreber => "5600",
            Self::FestucaOvinaSensuLato => "5610",
            Self::FestucaPratensisHudson => "5620",
            Self::FestucaRubraSensuLato => "5630",
            Self::FicusBenjamina => "5640",
            Self::FicusCarica5650 => "5650",
            Self::FoeniculumVulgareMil5660 => "5660",
            Self::FoeniculumVulgareMil5670 => "5670",
            Self::ForsythiaVahl => "5680",
            Self::Fragaria => "5690",
            Self::Fuchsia5700 => "5700",
            Self::GazaniaHybriden => "5710",
            Self::Gentiana => "5720",
            Self::Gerbera5730 => "5730",
            Self::GinkgoBiloba => "5740",
            Self::GlycineMaxMerr => "5750",
            Self::HebeCommExJuss => "5760",
            Self::HelianthusAnnuus => "5770",
            Self::HelianthusTuberosus => "5780",
            Self::HelichrysumItalicumRothGussone => "5790",
            Self::HeliotropiumArborescens => "5800",
            Self::Helleborus5810 => "5810",
            Self::Hippophae => "5820",
            Self::HordeumVulgareSensuLato5830 => "5830",
            Self::HordeumVulgareSensuLato5840 => "5840",
            Self::HumulusLupulus => "5850",
            Self::Hydrangea5860 => "5860",
            Self::HypericumAndrosaemum => "5870",
            Self::HypericumPerforatum => "5880",
            Self::HyssopusOfficinalis => "5890",
            Self::Ilex => "5900",
            Self::Impatiens => "5910",
            Self::ImpatiensWallerianaHybriden => "5920",
            Self::JuglansHybriden => "5930",
            Self::KalanchoeAdans => "5940",
            Self::LactucaSativa5950 => "5950",
            Self::LactucaSativa5960 => "5960",
            Self::LeontopodiumAlpinumCass => "5970",
            Self::LeucanthemumXSuperbumJWIngramBergmansExKent => "5980",
            Self::Lilium => "5990",
            Self::LimoniumMil => "6000",
            Self::LinumUsitatissimum => "6010",
            Self::LiquidambarStyraciflua6020 => "6020",
            Self::Lobelia => "6030",
            Self::LoliumPartim => "6040",
            Self::LoliumMultiflorumLam => "6050",
            Self::LoliumPerenne => "6060",
            Self::LoliumXBoucheanumKunth => "6070",
            Self::LoniceraNitidaWils => "6080",
            Self::LotusCorniculatus => "6090",
            Self::LupinusLuteus => "6100",
            Self::LupinusAlbus => "6110",
            Self::LupinusAngustifolius => "6120",
            Self::LupinusMutabilis => "6130",
            Self::LupinusNanusDouglas => "6140",
            Self::LycopersiconLycopersicumKarstenExFarw => "6150",
            Self::MalusMil6160 => "6160",
            Self::MalusMil6170 => "6170",
            Self::MalusMil6180 => "6180",
            Self::MalvaVerticillata => "6190",
            Self::MedicagoLupulina => "6200",
            Self::MedicagoSativa => "6210",
            Self::MelissaOfficinalis => "6220",
            Self::Nicotiana => "6230",
            Self::OcimumBasilicum => "6240",
            Self::OnobrychisViciifoliaScop => "6250",
            Self::Orchidaceae => "6260",
            Self::OriganumMajorana => "6270",
            Self::OriganumVulgare => "6280",
            Self::PelargoniumLhRitExAit => "6290",
            Self::PelargoniumGrandiflorumHybriden => "6300",
            Self::PetroselinumCrispumMillerNymanExAWHill6310 => "6310",
            Self::PetroselinumCrispumMillerNymanExAWHill6320 => "6320",
            Self::PetuniaJuss => "6330",
            Self::PhaceliaJuss => "6340",
            Self::PhalarisArundinacea => "6350",
            Self::PhaseolusCoccineus => "6360",
            Self::PhaseolusVulgaris6370 => "6370",
            Self::PhaseolusVulgaris6380 => "6380",
            Self::Phleum => "6390",
            Self::PhysocarpusCambessMaxim => "6400",
            Self::PiceaADietr => "6410",
            Self::Pinus6420 => "6420",
            Self::PisumSativumPartim6430 => "6430",
            Self::PisumSativumPartim6440 => "6440",
            Self::PisumSativumPartim6450 => "6450",
            Self::PisumSativumPartim6460 => "6460",
            Self::Poa => "6470",
            Self::PoaPratensis => "6480",
            Self::Populus6490 => "6490",
            Self::Prunus6500 => "6500",
            Self::Prunus6510 => "6510",
            Self::PrunusAvium6520 => "6520",
            Self::PrunusCerasus => "6530",
            Self::PrunusDomestica6540 => "6540",
            Self::PrunusPersicaBatsch => "6550",
            Self::PrunusSpinosa6560 => "6560",
            Self::PyracanthaMJRoem => "6570",
            Self::Pyrus6580 => "6580",
            Self::Pyrus6590 => "6590",
            Self::Quercus6600 => "6600",
            Self::Raphanobrassica => "6610",
            Self::RaphanusSativusVarNigerMillerSKerner => "6620",
            Self::RaphanusSativusVarOleiformisPers => "6630",
            Self::RaphanusSativusVarSativus => "6640",
            Self::RehmanniaLiboschExFischEtCAMey => "6650",
            Self::Rhododendron6660 => "6660",
            Self::RhododendronSimsiiPlanch => "6670",
            Self::Ribes6680 => "6680",
            Self::Ribes6690 => "6690",
            Self::RibesNigrum => "6700",
            Self::RibesXNidigrolariaREtABauer => "6710",
            Self::Rosa => "6720",
            Self::Rubus6730 => "6730",
            Self::Rubus6740 => "6740",
            Self::SaintpauliaHWend => "6750",
            Self::Salix6760 => "6760",
            Self::SanvitaliaLam => "6770",
            Self::SaturejaHortensis => "6780",
            Self::ScorzoneraHispanica => "6790",
            Self::Secale6800 => "6800",
            Self::Secale6810 => "6810",
            Self::SilybumMarianumGaertn => "6820",
            Self::SinapisAlba => "6830",
            Self::SinningiaNees => "6840",
            Self::Solanum => "6850",
            Self::SolanumTuberosum => "6860",
            Self::SpinaciaOleracea => "6870",
            Self::StreptocarpusLind => "6880",
            Self::SuteraRoth => "6890",
            Self::SymphoricarposDuham => "6900",
            Self::Syringa => "6910",
            Self::Tagetes => "6920",
            Self::TanacetumPartheniumSchultzBip => "6930",
            Self::Tilia => "6940",
            Self::TrifoliumAlexandrinum => "6950",
            Self::TrifoliumHybridum => "6960",
            Self::TrifoliumIncarnatum => "6970",
            Self::TrifoliumPratense => "6980",
            Self::TrifoliumRepens => "6990",
            Self::TrifoliumResupinatum => "7000",
            Self::TrisetumFlavescensPBeauv => "7010",
            Self::TriticumAestivumEmendFioriEtPao7020 => "7020",
            Self::TriticumAestivumEmendFioriEtPao7030 => "7030",
            Self::TriticumDurumDesf => "7040",
            Self::TriticumMonococcum => "7050",
            Self::TriticumSpelta => "7060",
            Self::Tulipa => "7070",
            Self::TussilagoFarfara => "7080",
            Self::Ulmus => "7090",
            Self::Urtica => "7100",
            Self::Vaccinium => "7110",
            Self::ValerianaOfficinalis => "7120",
            Self::ValerianellaLocustaLaterr => "7130",
            Self::Vallisneria => "7140",
            Self::ViciaPartim => "7150",
            Self::ViciaFabaPartim7160 => "7160",
            Self::ViciaFabaPartim7170 => "7170",
            Self::ViciaSativa => "7180",
            Self::VincaMinor => "7190",
            Self::VitexAgnusCastus => "7200",
            Self::Vitis => "7210",
            Self::VitisVinifera => "7220",
            Self::VrieseaSplendensBrongnLem => "7230",
            Self::ZantedeschiaSpreng => "7240",
            Self::ZeaMays => "7250",
            Self::XFestulolium => "7260",
            Self::XTriticosecaleWittm7270 => "7270",
            Self::XTriticosecaleWittm7280 => "7280",
            Self::Unknown => "9999",
            Self::Other(s) => s,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ecitygml_core::model::vegetation::values::SpeciesValue;
    use egml::model::basic_types::Code;

    #[test]
    fn round_trips_known_codes() {
        for (code, value) in [
            ("1000", Sig3dSpeciesValue::Picea),
            ("9999", Sig3dSpeciesValue::Unknown),
        ] {
            assert_eq!(Sig3dSpeciesValue::from_code_value(code), value);
            assert_eq!(value.to_code_value(), code);
        }
    }

    #[test]
    fn unrecognized_code_in_this_code_space_falls_back_to_other() {
        let value = Sig3dSpeciesValue::from_code_value("999999");
        assert_eq!(value, Sig3dSpeciesValue::Other("999999".to_string()));
        assert_eq!(value.to_code_value(), "999999");
    }

    #[test]
    fn interprets_bare_code_with_no_code_space() {
        let wrapped = SpeciesValue::from(Code::new("1000"));
        assert_eq!(
            wrapped.interpret::<Sig3dSpeciesValue>(),
            Some(Sig3dSpeciesValue::Picea)
        );
    }

    #[test]
    fn does_not_interpret_a_different_code_space() {
        let wrapped = SpeciesValue::from(Code::with_code_space(
            "https://example.org/local-codes",
            "1000",
        ));
        assert_eq!(wrapped.interpret::<Sig3dSpeciesValue>(), None);
    }
}
