use ecitygml_core::model::common::CodeListValue;

/// The SIG3D standard code list `_AbstractBuilding_usage.xml` (version 2.0).
///
/// <https://www.sig3d.de/codelists/standard/building/2.0/_AbstractBuilding_usage.xml>
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Sig3dBuildingUsageValue {
    ResidentialBuilding,
    Tenement,
    Hostel,
    ResidentialAndAdministrationBuilding,
    ResidentialAndOfficeBuilding,
    ResidentialAndBusinessBuilding,
    ResidentialAndPlantBuilding,
    AgrarianAndForestryBuilding,
    ResidentialAndCommercialBuilding,
    ForestersLodge,
    HolidayHouse,
    SummerHouse,
    OfficeBuilding,
    CreditInstitution,
    Insurance,
    BusinessBuilding,
    DepartmentStore,
    ShoppingCentre,
    Kiosk,
    Pharmacy,
    Pavilion,
    Hotel,
    YouthHostel,
    CampsiteBuilding,
    Restaurant,
    Cantine,
    RecreationalSite,
    FunctionRoom,
    Cinema,
    BowlingAlley,
    Casino,
    IndustrialBuilding,
    Factory,
    Workshop,
    PetrolGasStation,
    WashingPlant,
    ColdStore,
    Depot,
    BuildingForResearchPurposes,
    Quarry,
    SaltWorks,
    MiscellaneousIndustrialBuilding,
    Mill,
    Windmill,
    WaterMill,
    BucketElevator,
    WeatherStation,
    TrafficAssetsOffice,
    StreetMaintenance,
    WaitingHall,
    SignalControlBox,
    EngineShed,
    SignalBoxOrStopSignal,
    PlantBuildingForAirTraffic,
    Hangar,
    PlantBuildingForShipping,
    Shipyard,
    Dock,
    PlantBuildingForCanalLock,
    Boathouse,
    PlantBuildingForCablecar,
    MultiStoreyCarPark,
    ParkingLevel,
    Garage,
    VehicleHall,
    UndergroundGarage,
    BuildingForSupply,
    Waterworks,
    PumpStation,
    WaterBasin,
    ElectricPowerStation,
    TransformerStation,
    Converter,
    Reactor,
    TurbineHouse,
    BoilerHouse,
    BuildingForTelecommunications,
    GasWorks,
    HeatPlant,
    PumpingStation,
    BuildingForDisposal,
    BuildingForEffluentDisposal,
    BuildingForFilterPlant,
    Toilet,
    RubbishBunker,
    BuildingForRubbishIncineration,
    BuildingForRubbishDisposal,
    BuildingForAgrarianAndForestry,
    Barn,
    Stall,
    EquestrianHall,
    AlpineCabin,
    HuntingLodge,
    Arboretum,
    GlassHouse,
    MoveableGlassHouse,
    PublicBuilding,
    AdministrationBuilding,
    Parliament,
    Guildhall,
    PostOffice,
    CustomsOffice,
    Court,
    EmbassyOrConsulate,
    DistrictAdministration,
    DistrictGovernment,
    TaxOffice,
    BuildingForEducationAndResearch,
    ComprehensiveSchool,
    VocationalSchool,
    CollegeOrUniversity,
    ResearchEstablishment,
    BuildingForCulturalPurposes,
    Castle,
    TheatreOrOpera,
    ConcertBuilding,
    Museum,
    BroadcastingBuilding,
    ActivityBuilding,
    Library,
    Fort,
    ReligiousBuilding,
    Church,
    Synagogue,
    Chapel,
    CommunityCenter,
    PlaceOfWorship,
    Mosque,
    Temple,
    Convent,
    BuildingForHealthCare,
    Hospital,
    HealingCentreOrCareHome,
    HealthCentreOrOutpatientsClinic,
    BuildingForSocialPurposes,
    YouthCentre,
    SeniorsCentre,
    HomelessShelter,
    KindergartenOrNursery,
    AsylumSeekersHome,
    PoliceStation,
    FireStation,
    Barracks,
    Bunker,
    PenitentiaryOrPrison,
    CemeteryBuilding,
    FuneralParlor,
    Crematorium,
    TrainStation,
    AirportBuilding,
    BuildingForUndergroundStation,
    BuildingForTramway,
    BuildingForBusStation,
    ShippingTerminal,
    BuildingForRecuperationPurposes,
    BuildingForSportPurposes,
    SportsHall,
    BuildingForSportsField,
    SwimmingBaths,
    IndoorSwimmingPool,
    Sanatorium,
    ZooBuilding,
    GreenHouse,
    BotanicalShowHouse,
    Bothy,
    TouristInformationCentre,
    Others,
    /// A value within this code list's codeSpace that isn't one of the
    /// entries above.
    Other(String),
}

impl CodeListValue for Sig3dBuildingUsageValue {
    const CODE_SPACE: &'static str =
        "http://www.sig3d.org/codelists/citygml/2.0/building/2.0/_AbstractBuilding_usage.xml";

    fn from_code_value(value: &str) -> Self {
        match value {
            "1000" => Self::ResidentialBuilding,
            "1010" => Self::Tenement,
            "1020" => Self::Hostel,
            "1030" => Self::ResidentialAndAdministrationBuilding,
            "1040" => Self::ResidentialAndOfficeBuilding,
            "1050" => Self::ResidentialAndBusinessBuilding,
            "1060" => Self::ResidentialAndPlantBuilding,
            "1070" => Self::AgrarianAndForestryBuilding,
            "1080" => Self::ResidentialAndCommercialBuilding,
            "1090" => Self::ForestersLodge,
            "1100" => Self::HolidayHouse,
            "1110" => Self::SummerHouse,
            "1120" => Self::OfficeBuilding,
            "1130" => Self::CreditInstitution,
            "1140" => Self::Insurance,
            "1150" => Self::BusinessBuilding,
            "1160" => Self::DepartmentStore,
            "1170" => Self::ShoppingCentre,
            "1180" => Self::Kiosk,
            "1190" => Self::Pharmacy,
            "1200" => Self::Pavilion,
            "1210" => Self::Hotel,
            "1220" => Self::YouthHostel,
            "1230" => Self::CampsiteBuilding,
            "1240" => Self::Restaurant,
            "1250" => Self::Cantine,
            "1260" => Self::RecreationalSite,
            "1270" => Self::FunctionRoom,
            "1280" => Self::Cinema,
            "1290" => Self::BowlingAlley,
            "1300" => Self::Casino,
            "1310" => Self::IndustrialBuilding,
            "1320" => Self::Factory,
            "1330" => Self::Workshop,
            "1340" => Self::PetrolGasStation,
            "1350" => Self::WashingPlant,
            "1360" => Self::ColdStore,
            "1370" => Self::Depot,
            "1380" => Self::BuildingForResearchPurposes,
            "1390" => Self::Quarry,
            "1400" => Self::SaltWorks,
            "1410" => Self::MiscellaneousIndustrialBuilding,
            "1420" => Self::Mill,
            "1430" => Self::Windmill,
            "1440" => Self::WaterMill,
            "1450" => Self::BucketElevator,
            "1460" => Self::WeatherStation,
            "1470" => Self::TrafficAssetsOffice,
            "1480" => Self::StreetMaintenance,
            "1490" => Self::WaitingHall,
            "1500" => Self::SignalControlBox,
            "1510" => Self::EngineShed,
            "1520" => Self::SignalBoxOrStopSignal,
            "1530" => Self::PlantBuildingForAirTraffic,
            "1540" => Self::Hangar,
            "1550" => Self::PlantBuildingForShipping,
            "1560" => Self::Shipyard,
            "1570" => Self::Dock,
            "1580" => Self::PlantBuildingForCanalLock,
            "1590" => Self::Boathouse,
            "1600" => Self::PlantBuildingForCablecar,
            "1610" => Self::MultiStoreyCarPark,
            "1620" => Self::ParkingLevel,
            "1630" => Self::Garage,
            "1640" => Self::VehicleHall,
            "1650" => Self::UndergroundGarage,
            "1660" => Self::BuildingForSupply,
            "1670" => Self::Waterworks,
            "1680" => Self::PumpStation,
            "1690" => Self::WaterBasin,
            "1700" => Self::ElectricPowerStation,
            "1710" => Self::TransformerStation,
            "1720" => Self::Converter,
            "1730" => Self::Reactor,
            "1740" => Self::TurbineHouse,
            "1750" => Self::BoilerHouse,
            "1760" => Self::BuildingForTelecommunications,
            "1770" => Self::GasWorks,
            "1780" => Self::HeatPlant,
            "1790" => Self::PumpingStation,
            "1800" => Self::BuildingForDisposal,
            "1810" => Self::BuildingForEffluentDisposal,
            "1820" => Self::BuildingForFilterPlant,
            "1830" => Self::Toilet,
            "1840" => Self::RubbishBunker,
            "1850" => Self::BuildingForRubbishIncineration,
            "1860" => Self::BuildingForRubbishDisposal,
            "1870" => Self::BuildingForAgrarianAndForestry,
            "1880" => Self::Barn,
            "1890" => Self::Stall,
            "1900" => Self::EquestrianHall,
            "1910" => Self::AlpineCabin,
            "1920" => Self::HuntingLodge,
            "1930" => Self::Arboretum,
            "1940" => Self::GlassHouse,
            "1950" => Self::MoveableGlassHouse,
            "1960" => Self::PublicBuilding,
            "1970" => Self::AdministrationBuilding,
            "1980" => Self::Parliament,
            "1990" => Self::Guildhall,
            "2000" => Self::PostOffice,
            "2010" => Self::CustomsOffice,
            "2020" => Self::Court,
            "2030" => Self::EmbassyOrConsulate,
            "2040" => Self::DistrictAdministration,
            "2050" => Self::DistrictGovernment,
            "2060" => Self::TaxOffice,
            "2070" => Self::BuildingForEducationAndResearch,
            "2080" => Self::ComprehensiveSchool,
            "2090" => Self::VocationalSchool,
            "2100" => Self::CollegeOrUniversity,
            "2110" => Self::ResearchEstablishment,
            "2120" => Self::BuildingForCulturalPurposes,
            "2130" => Self::Castle,
            "2140" => Self::TheatreOrOpera,
            "2150" => Self::ConcertBuilding,
            "2160" => Self::Museum,
            "2170" => Self::BroadcastingBuilding,
            "2180" => Self::ActivityBuilding,
            "2190" => Self::Library,
            "2200" => Self::Fort,
            "2210" => Self::ReligiousBuilding,
            "2220" => Self::Church,
            "2230" => Self::Synagogue,
            "2240" => Self::Chapel,
            "2250" => Self::CommunityCenter,
            "2260" => Self::PlaceOfWorship,
            "2270" => Self::Mosque,
            "2280" => Self::Temple,
            "2290" => Self::Convent,
            "2300" => Self::BuildingForHealthCare,
            "2310" => Self::Hospital,
            "2320" => Self::HealingCentreOrCareHome,
            "2330" => Self::HealthCentreOrOutpatientsClinic,
            "2340" => Self::BuildingForSocialPurposes,
            "2350" => Self::YouthCentre,
            "2360" => Self::SeniorsCentre,
            "2370" => Self::HomelessShelter,
            "2380" => Self::KindergartenOrNursery,
            "2390" => Self::AsylumSeekersHome,
            "2400" => Self::PoliceStation,
            "2410" => Self::FireStation,
            "2420" => Self::Barracks,
            "2430" => Self::Bunker,
            "2440" => Self::PenitentiaryOrPrison,
            "2450" => Self::CemeteryBuilding,
            "2460" => Self::FuneralParlor,
            "2470" => Self::Crematorium,
            "2480" => Self::TrainStation,
            "2490" => Self::AirportBuilding,
            "2500" => Self::BuildingForUndergroundStation,
            "2510" => Self::BuildingForTramway,
            "2520" => Self::BuildingForBusStation,
            "2530" => Self::ShippingTerminal,
            "2540" => Self::BuildingForRecuperationPurposes,
            "2550" => Self::BuildingForSportPurposes,
            "2560" => Self::SportsHall,
            "2570" => Self::BuildingForSportsField,
            "2580" => Self::SwimmingBaths,
            "2590" => Self::IndoorSwimmingPool,
            "2600" => Self::Sanatorium,
            "2610" => Self::ZooBuilding,
            "2620" => Self::GreenHouse,
            "2630" => Self::BotanicalShowHouse,
            "2640" => Self::Bothy,
            "2650" => Self::TouristInformationCentre,
            "2700" => Self::Others,
            other => Self::Other(other.to_string()),
        }
    }

    fn to_code_value(&self) -> &str {
        match self {
            Self::ResidentialBuilding => "1000",
            Self::Tenement => "1010",
            Self::Hostel => "1020",
            Self::ResidentialAndAdministrationBuilding => "1030",
            Self::ResidentialAndOfficeBuilding => "1040",
            Self::ResidentialAndBusinessBuilding => "1050",
            Self::ResidentialAndPlantBuilding => "1060",
            Self::AgrarianAndForestryBuilding => "1070",
            Self::ResidentialAndCommercialBuilding => "1080",
            Self::ForestersLodge => "1090",
            Self::HolidayHouse => "1100",
            Self::SummerHouse => "1110",
            Self::OfficeBuilding => "1120",
            Self::CreditInstitution => "1130",
            Self::Insurance => "1140",
            Self::BusinessBuilding => "1150",
            Self::DepartmentStore => "1160",
            Self::ShoppingCentre => "1170",
            Self::Kiosk => "1180",
            Self::Pharmacy => "1190",
            Self::Pavilion => "1200",
            Self::Hotel => "1210",
            Self::YouthHostel => "1220",
            Self::CampsiteBuilding => "1230",
            Self::Restaurant => "1240",
            Self::Cantine => "1250",
            Self::RecreationalSite => "1260",
            Self::FunctionRoom => "1270",
            Self::Cinema => "1280",
            Self::BowlingAlley => "1290",
            Self::Casino => "1300",
            Self::IndustrialBuilding => "1310",
            Self::Factory => "1320",
            Self::Workshop => "1330",
            Self::PetrolGasStation => "1340",
            Self::WashingPlant => "1350",
            Self::ColdStore => "1360",
            Self::Depot => "1370",
            Self::BuildingForResearchPurposes => "1380",
            Self::Quarry => "1390",
            Self::SaltWorks => "1400",
            Self::MiscellaneousIndustrialBuilding => "1410",
            Self::Mill => "1420",
            Self::Windmill => "1430",
            Self::WaterMill => "1440",
            Self::BucketElevator => "1450",
            Self::WeatherStation => "1460",
            Self::TrafficAssetsOffice => "1470",
            Self::StreetMaintenance => "1480",
            Self::WaitingHall => "1490",
            Self::SignalControlBox => "1500",
            Self::EngineShed => "1510",
            Self::SignalBoxOrStopSignal => "1520",
            Self::PlantBuildingForAirTraffic => "1530",
            Self::Hangar => "1540",
            Self::PlantBuildingForShipping => "1550",
            Self::Shipyard => "1560",
            Self::Dock => "1570",
            Self::PlantBuildingForCanalLock => "1580",
            Self::Boathouse => "1590",
            Self::PlantBuildingForCablecar => "1600",
            Self::MultiStoreyCarPark => "1610",
            Self::ParkingLevel => "1620",
            Self::Garage => "1630",
            Self::VehicleHall => "1640",
            Self::UndergroundGarage => "1650",
            Self::BuildingForSupply => "1660",
            Self::Waterworks => "1670",
            Self::PumpStation => "1680",
            Self::WaterBasin => "1690",
            Self::ElectricPowerStation => "1700",
            Self::TransformerStation => "1710",
            Self::Converter => "1720",
            Self::Reactor => "1730",
            Self::TurbineHouse => "1740",
            Self::BoilerHouse => "1750",
            Self::BuildingForTelecommunications => "1760",
            Self::GasWorks => "1770",
            Self::HeatPlant => "1780",
            Self::PumpingStation => "1790",
            Self::BuildingForDisposal => "1800",
            Self::BuildingForEffluentDisposal => "1810",
            Self::BuildingForFilterPlant => "1820",
            Self::Toilet => "1830",
            Self::RubbishBunker => "1840",
            Self::BuildingForRubbishIncineration => "1850",
            Self::BuildingForRubbishDisposal => "1860",
            Self::BuildingForAgrarianAndForestry => "1870",
            Self::Barn => "1880",
            Self::Stall => "1890",
            Self::EquestrianHall => "1900",
            Self::AlpineCabin => "1910",
            Self::HuntingLodge => "1920",
            Self::Arboretum => "1930",
            Self::GlassHouse => "1940",
            Self::MoveableGlassHouse => "1950",
            Self::PublicBuilding => "1960",
            Self::AdministrationBuilding => "1970",
            Self::Parliament => "1980",
            Self::Guildhall => "1990",
            Self::PostOffice => "2000",
            Self::CustomsOffice => "2010",
            Self::Court => "2020",
            Self::EmbassyOrConsulate => "2030",
            Self::DistrictAdministration => "2040",
            Self::DistrictGovernment => "2050",
            Self::TaxOffice => "2060",
            Self::BuildingForEducationAndResearch => "2070",
            Self::ComprehensiveSchool => "2080",
            Self::VocationalSchool => "2090",
            Self::CollegeOrUniversity => "2100",
            Self::ResearchEstablishment => "2110",
            Self::BuildingForCulturalPurposes => "2120",
            Self::Castle => "2130",
            Self::TheatreOrOpera => "2140",
            Self::ConcertBuilding => "2150",
            Self::Museum => "2160",
            Self::BroadcastingBuilding => "2170",
            Self::ActivityBuilding => "2180",
            Self::Library => "2190",
            Self::Fort => "2200",
            Self::ReligiousBuilding => "2210",
            Self::Church => "2220",
            Self::Synagogue => "2230",
            Self::Chapel => "2240",
            Self::CommunityCenter => "2250",
            Self::PlaceOfWorship => "2260",
            Self::Mosque => "2270",
            Self::Temple => "2280",
            Self::Convent => "2290",
            Self::BuildingForHealthCare => "2300",
            Self::Hospital => "2310",
            Self::HealingCentreOrCareHome => "2320",
            Self::HealthCentreOrOutpatientsClinic => "2330",
            Self::BuildingForSocialPurposes => "2340",
            Self::YouthCentre => "2350",
            Self::SeniorsCentre => "2360",
            Self::HomelessShelter => "2370",
            Self::KindergartenOrNursery => "2380",
            Self::AsylumSeekersHome => "2390",
            Self::PoliceStation => "2400",
            Self::FireStation => "2410",
            Self::Barracks => "2420",
            Self::Bunker => "2430",
            Self::PenitentiaryOrPrison => "2440",
            Self::CemeteryBuilding => "2450",
            Self::FuneralParlor => "2460",
            Self::Crematorium => "2470",
            Self::TrainStation => "2480",
            Self::AirportBuilding => "2490",
            Self::BuildingForUndergroundStation => "2500",
            Self::BuildingForTramway => "2510",
            Self::BuildingForBusStation => "2520",
            Self::ShippingTerminal => "2530",
            Self::BuildingForRecuperationPurposes => "2540",
            Self::BuildingForSportPurposes => "2550",
            Self::SportsHall => "2560",
            Self::BuildingForSportsField => "2570",
            Self::SwimmingBaths => "2580",
            Self::IndoorSwimmingPool => "2590",
            Self::Sanatorium => "2600",
            Self::ZooBuilding => "2610",
            Self::GreenHouse => "2620",
            Self::BotanicalShowHouse => "2630",
            Self::Bothy => "2640",
            Self::TouristInformationCentre => "2650",
            Self::Others => "2700",
            Self::Other(s) => s,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ecitygml_core::model::building::values::BuildingUsageValue;
    use egml::model::basic_types::Code;

    #[test]
    fn round_trips_known_codes() {
        for (code, value) in [
            ("1000", Sig3dBuildingUsageValue::ResidentialBuilding),
            ("2700", Sig3dBuildingUsageValue::Others),
        ] {
            assert_eq!(Sig3dBuildingUsageValue::from_code_value(code), value);
            assert_eq!(value.to_code_value(), code);
        }
    }

    #[test]
    fn unrecognized_code_in_this_code_space_falls_back_to_other() {
        let value = Sig3dBuildingUsageValue::from_code_value("999999");
        assert_eq!(value, Sig3dBuildingUsageValue::Other("999999".to_string()));
        assert_eq!(value.to_code_value(), "999999");
    }

    #[test]
    fn interprets_bare_code_with_no_code_space() {
        let wrapped = BuildingUsageValue::from(Code::new("1000"));
        assert_eq!(
            wrapped.interpret::<Sig3dBuildingUsageValue>(),
            Some(Sig3dBuildingUsageValue::ResidentialBuilding)
        );
    }

    #[test]
    fn does_not_interpret_a_different_code_space() {
        let wrapped = BuildingUsageValue::from(Code::with_code_space(
            "https://example.org/local-codes",
            "1000",
        ));
        assert_eq!(wrapped.interpret::<Sig3dBuildingUsageValue>(), None);
    }
}
