use ecitygml_core::model::common::CodeListValue;

/// The SIG3D standard code list `Room_function.xml` (version 2.0).
///
/// <https://www.sig3d.de/codelists/standard/building/2.0/Room_function.xml>
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Sig3dBuildingRoomFunctionValue {
    LivingRoom,
    Bedroom,
    Kitchen,
    Hall,
    BathWashroom,
    Toilet,
    Stairs,
    HomeOffice,
    UtilityRoom1080,
    DiningRoom1090,
    CommonRoom,
    PartyRoom,
    Nursery,
    StoreRoom1130,
    CanteenCommonKitchen,
    Storeroom,
    BalconyGallery,
    Terrace,
    DryingRoom,
    Heatingroom,
    FuelDepot,
    HobbyRoom,
    StableHovel,
    CashOffice,
    TicketOffice1310,
    ConferenceRoom,
    Reception1330,
    SalesRoom,
    StoreRoom1350,
    Delivery,
    LoungeCommonRoom,
    Escalator,
    GuestToilet,
    StrongRoom,
    Office1500,
    EntranceHall,
    Elevator,
    Canteen,
    TeaKitchenCoffeeKitchen,
    Archive,
    CitizenOffice,
    ConferenceHall,
    CopierRoomBlueprintRoom,
    Information,
    ComputerRoom,
    PrinterPlotterRoom,
    Reception1700,
    GuestRoom,
    Bar,
    BreakfastRoom,
    DiningRoom1740,
    CelebrationRoom,
    Pub,
    BeerGarden,
    Restaurant,
    CoolStore,
    BowlingAlleyShootAlley,
    Lounge,
    CanteenKitchen,
    Stage,
    Auditorium,
    VipBox,
    ProjectionRoom,
    DressingRoom1940,
    Cabin,
    Showroom,
    EquipmentOrProps,
    MakeUpRoom,
    RecordingStudio,
    SoundStudio,
    MusicArchive,
    Administration,
    TicketOffice2030,
    Library,
    MediaRoom2050,
    DressingRoom2060,
    SportRoom,
    EquipmentRoom,
    Platform,
    SwimmingPool,
    Slide,
    RelaxationRoom2120,
    Sauna,
    FitnessRoom,
    Solarium,
    Catering,
    Showers,
    Tribune,
    SeatingStandingCapacity,
    CashPoint,
    Vivarium,
    Enclosure,
    Aquarium,
    Terrarium,
    Aviary,
    Menagerie,
    Stables,
    Greenhouse,
    FoodSilo,
    Hayloft,
    MotorPool2330,
    Barn,
    RidingHall,
    HorseBox,
    HuntingLodge,
    WasteContainer,
    MotorPool2410,
    WashingBay,
    InstallationsRoom,
    MonitoringRoom,
    HeatingSystem,
    PublicUtilityUse,
    PumpRoom,
    EffluentTreatment,
    TreatmentInstallation,
    RecyclingInstallation,
    Chancel,
    Sacristy,
    BellTower,
    BaptismRoom,
    Confessional,
    Benches,
    Pulpit,
    Lobby,
    Parish,
    Chapel,
    PoliceStation,
    Headquarters,
    PrisonCell,
    MotorPoolHall,
    FireBrigadeEmergencyVehicle,
    RelaxationRoom2750,
    ToolPipeStore,
    EmergencyCallCenter,
    ArmsDepot,
    AmmunitionDump,
    VehicleHall,
    PanicRoom,
    SatelliteReceiver,
    CommunicationRoom,
    IndustrialBuilding,
    ProductionBuilding,
    FactoryBuilding,
    Workshop,
    StorageDepot,
    ColdStorage,
    Store,
    StationConcourse,
    Track,
    TicketOffice3120,
    WaitingHall,
    EngineShed,
    SignalBox,
    DepartureTerminal,
    CheckOutCounter,
    CheckInCounter,
    Check,
    BaggageCarousel,
    SecurityCheck,
    Classroom,
    StaffRoom,
    BreakOrRecessHall,
    Laboratory,
    UtilityRoom3340,
    MediaRoom3350,
    ScienceLaboratory,
    SportsHall,
    SchoolLibrary,
    Office3390,
    LectureTheatre,
    Refectory,
    FunctionRoom,
    /// A value within this code list's codeSpace that isn't one of the
    /// entries above.
    Other(String),
}

impl CodeListValue for Sig3dBuildingRoomFunctionValue {
    const CODE_SPACE: &'static str =
        "http://www.sig3d.org/codelists/citygml/2.0/building/2.0/Room_function.xml";

    fn from_code_value(value: &str) -> Self {
        match value {
            "1000" => Self::LivingRoom,
            "1010" => Self::Bedroom,
            "1020" => Self::Kitchen,
            "1030" => Self::Hall,
            "1040" => Self::BathWashroom,
            "1050" => Self::Toilet,
            "1060" => Self::Stairs,
            "1070" => Self::HomeOffice,
            "1080" => Self::UtilityRoom1080,
            "1090" => Self::DiningRoom1090,
            "1100" => Self::CommonRoom,
            "1110" => Self::PartyRoom,
            "1120" => Self::Nursery,
            "1130" => Self::StoreRoom1130,
            "1140" => Self::CanteenCommonKitchen,
            "1150" => Self::Storeroom,
            "1160" => Self::BalconyGallery,
            "1170" => Self::Terrace,
            "1180" => Self::DryingRoom,
            "1190" => Self::Heatingroom,
            "1200" => Self::FuelDepot,
            "1210" => Self::HobbyRoom,
            "1220" => Self::StableHovel,
            "1300" => Self::CashOffice,
            "1310" => Self::TicketOffice1310,
            "1320" => Self::ConferenceRoom,
            "1330" => Self::Reception1330,
            "1340" => Self::SalesRoom,
            "1350" => Self::StoreRoom1350,
            "1360" => Self::Delivery,
            "1370" => Self::LoungeCommonRoom,
            "1380" => Self::Escalator,
            "1390" => Self::GuestToilet,
            "1400" => Self::StrongRoom,
            "1500" => Self::Office1500,
            "1510" => Self::EntranceHall,
            "1520" => Self::Elevator,
            "1530" => Self::Canteen,
            "1540" => Self::TeaKitchenCoffeeKitchen,
            "1550" => Self::Archive,
            "1560" => Self::CitizenOffice,
            "1570" => Self::ConferenceHall,
            "1580" => Self::CopierRoomBlueprintRoom,
            "1590" => Self::Information,
            "1600" => Self::ComputerRoom,
            "1610" => Self::PrinterPlotterRoom,
            "1700" => Self::Reception1700,
            "1710" => Self::GuestRoom,
            "1720" => Self::Bar,
            "1730" => Self::BreakfastRoom,
            "1740" => Self::DiningRoom1740,
            "1750" => Self::CelebrationRoom,
            "1760" => Self::Pub,
            "1770" => Self::BeerGarden,
            "1780" => Self::Restaurant,
            "1790" => Self::CoolStore,
            "1800" => Self::BowlingAlleyShootAlley,
            "1810" => Self::Lounge,
            "1820" => Self::CanteenKitchen,
            "1900" => Self::Stage,
            "1910" => Self::Auditorium,
            "1920" => Self::VipBox,
            "1930" => Self::ProjectionRoom,
            "1940" => Self::DressingRoom1940,
            "1950" => Self::Cabin,
            "1960" => Self::Showroom,
            "1970" => Self::EquipmentOrProps,
            "1980" => Self::MakeUpRoom,
            "1990" => Self::RecordingStudio,
            "2000" => Self::SoundStudio,
            "2010" => Self::MusicArchive,
            "2020" => Self::Administration,
            "2030" => Self::TicketOffice2030,
            "2040" => Self::Library,
            "2050" => Self::MediaRoom2050,
            "2060" => Self::DressingRoom2060,
            "2070" => Self::SportRoom,
            "2080" => Self::EquipmentRoom,
            "2090" => Self::Platform,
            "2100" => Self::SwimmingPool,
            "2110" => Self::Slide,
            "2120" => Self::RelaxationRoom2120,
            "2130" => Self::Sauna,
            "2140" => Self::FitnessRoom,
            "2150" => Self::Solarium,
            "2160" => Self::Catering,
            "2170" => Self::Showers,
            "2200" => Self::Tribune,
            "2210" => Self::SeatingStandingCapacity,
            "2220" => Self::CashPoint,
            "2230" => Self::Vivarium,
            "2240" => Self::Enclosure,
            "2250" => Self::Aquarium,
            "2260" => Self::Terrarium,
            "2270" => Self::Aviary,
            "2280" => Self::Menagerie,
            "2290" => Self::Stables,
            "2300" => Self::Greenhouse,
            "2310" => Self::FoodSilo,
            "2320" => Self::Hayloft,
            "2330" => Self::MotorPool2330,
            "2340" => Self::Barn,
            "2350" => Self::RidingHall,
            "2360" => Self::HorseBox,
            "2370" => Self::HuntingLodge,
            "2400" => Self::WasteContainer,
            "2410" => Self::MotorPool2410,
            "2420" => Self::WashingBay,
            "2430" => Self::InstallationsRoom,
            "2440" => Self::MonitoringRoom,
            "2450" => Self::HeatingSystem,
            "2460" => Self::PublicUtilityUse,
            "2470" => Self::PumpRoom,
            "2480" => Self::EffluentTreatment,
            "2490" => Self::TreatmentInstallation,
            "2500" => Self::RecyclingInstallation,
            "2600" => Self::Chancel,
            "2610" => Self::Sacristy,
            "2620" => Self::BellTower,
            "2630" => Self::BaptismRoom,
            "2640" => Self::Confessional,
            "2650" => Self::Benches,
            "2660" => Self::Pulpit,
            "2670" => Self::Lobby,
            "2680" => Self::Parish,
            "2690" => Self::Chapel,
            "2700" => Self::PoliceStation,
            "2710" => Self::Headquarters,
            "2720" => Self::PrisonCell,
            "2730" => Self::MotorPoolHall,
            "2740" => Self::FireBrigadeEmergencyVehicle,
            "2750" => Self::RelaxationRoom2750,
            "2760" => Self::ToolPipeStore,
            "2770" => Self::EmergencyCallCenter,
            "2780" => Self::ArmsDepot,
            "2790" => Self::AmmunitionDump,
            "2800" => Self::VehicleHall,
            "2810" => Self::PanicRoom,
            "2900" => Self::SatelliteReceiver,
            "2910" => Self::CommunicationRoom,
            "3000" => Self::IndustrialBuilding,
            "3010" => Self::ProductionBuilding,
            "3020" => Self::FactoryBuilding,
            "3030" => Self::Workshop,
            "3040" => Self::StorageDepot,
            "3050" => Self::ColdStorage,
            "3060" => Self::Store,
            "3100" => Self::StationConcourse,
            "3110" => Self::Track,
            "3120" => Self::TicketOffice3120,
            "3130" => Self::WaitingHall,
            "3140" => Self::EngineShed,
            "3150" => Self::SignalBox,
            "3160" => Self::DepartureTerminal,
            "3170" => Self::CheckOutCounter,
            "3180" => Self::CheckInCounter,
            "3190" => Self::Check,
            "3200" => Self::BaggageCarousel,
            "3210" => Self::SecurityCheck,
            "3300" => Self::Classroom,
            "3310" => Self::StaffRoom,
            "3320" => Self::BreakOrRecessHall,
            "3330" => Self::Laboratory,
            "3340" => Self::UtilityRoom3340,
            "3350" => Self::MediaRoom3350,
            "3360" => Self::ScienceLaboratory,
            "3370" => Self::SportsHall,
            "3380" => Self::SchoolLibrary,
            "3390" => Self::Office3390,
            "3400" => Self::LectureTheatre,
            "3410" => Self::Refectory,
            "3420" => Self::FunctionRoom,
            other => Self::Other(other.to_string()),
        }
    }

    fn to_code_value(&self) -> &str {
        match self {
            Self::LivingRoom => "1000",
            Self::Bedroom => "1010",
            Self::Kitchen => "1020",
            Self::Hall => "1030",
            Self::BathWashroom => "1040",
            Self::Toilet => "1050",
            Self::Stairs => "1060",
            Self::HomeOffice => "1070",
            Self::UtilityRoom1080 => "1080",
            Self::DiningRoom1090 => "1090",
            Self::CommonRoom => "1100",
            Self::PartyRoom => "1110",
            Self::Nursery => "1120",
            Self::StoreRoom1130 => "1130",
            Self::CanteenCommonKitchen => "1140",
            Self::Storeroom => "1150",
            Self::BalconyGallery => "1160",
            Self::Terrace => "1170",
            Self::DryingRoom => "1180",
            Self::Heatingroom => "1190",
            Self::FuelDepot => "1200",
            Self::HobbyRoom => "1210",
            Self::StableHovel => "1220",
            Self::CashOffice => "1300",
            Self::TicketOffice1310 => "1310",
            Self::ConferenceRoom => "1320",
            Self::Reception1330 => "1330",
            Self::SalesRoom => "1340",
            Self::StoreRoom1350 => "1350",
            Self::Delivery => "1360",
            Self::LoungeCommonRoom => "1370",
            Self::Escalator => "1380",
            Self::GuestToilet => "1390",
            Self::StrongRoom => "1400",
            Self::Office1500 => "1500",
            Self::EntranceHall => "1510",
            Self::Elevator => "1520",
            Self::Canteen => "1530",
            Self::TeaKitchenCoffeeKitchen => "1540",
            Self::Archive => "1550",
            Self::CitizenOffice => "1560",
            Self::ConferenceHall => "1570",
            Self::CopierRoomBlueprintRoom => "1580",
            Self::Information => "1590",
            Self::ComputerRoom => "1600",
            Self::PrinterPlotterRoom => "1610",
            Self::Reception1700 => "1700",
            Self::GuestRoom => "1710",
            Self::Bar => "1720",
            Self::BreakfastRoom => "1730",
            Self::DiningRoom1740 => "1740",
            Self::CelebrationRoom => "1750",
            Self::Pub => "1760",
            Self::BeerGarden => "1770",
            Self::Restaurant => "1780",
            Self::CoolStore => "1790",
            Self::BowlingAlleyShootAlley => "1800",
            Self::Lounge => "1810",
            Self::CanteenKitchen => "1820",
            Self::Stage => "1900",
            Self::Auditorium => "1910",
            Self::VipBox => "1920",
            Self::ProjectionRoom => "1930",
            Self::DressingRoom1940 => "1940",
            Self::Cabin => "1950",
            Self::Showroom => "1960",
            Self::EquipmentOrProps => "1970",
            Self::MakeUpRoom => "1980",
            Self::RecordingStudio => "1990",
            Self::SoundStudio => "2000",
            Self::MusicArchive => "2010",
            Self::Administration => "2020",
            Self::TicketOffice2030 => "2030",
            Self::Library => "2040",
            Self::MediaRoom2050 => "2050",
            Self::DressingRoom2060 => "2060",
            Self::SportRoom => "2070",
            Self::EquipmentRoom => "2080",
            Self::Platform => "2090",
            Self::SwimmingPool => "2100",
            Self::Slide => "2110",
            Self::RelaxationRoom2120 => "2120",
            Self::Sauna => "2130",
            Self::FitnessRoom => "2140",
            Self::Solarium => "2150",
            Self::Catering => "2160",
            Self::Showers => "2170",
            Self::Tribune => "2200",
            Self::SeatingStandingCapacity => "2210",
            Self::CashPoint => "2220",
            Self::Vivarium => "2230",
            Self::Enclosure => "2240",
            Self::Aquarium => "2250",
            Self::Terrarium => "2260",
            Self::Aviary => "2270",
            Self::Menagerie => "2280",
            Self::Stables => "2290",
            Self::Greenhouse => "2300",
            Self::FoodSilo => "2310",
            Self::Hayloft => "2320",
            Self::MotorPool2330 => "2330",
            Self::Barn => "2340",
            Self::RidingHall => "2350",
            Self::HorseBox => "2360",
            Self::HuntingLodge => "2370",
            Self::WasteContainer => "2400",
            Self::MotorPool2410 => "2410",
            Self::WashingBay => "2420",
            Self::InstallationsRoom => "2430",
            Self::MonitoringRoom => "2440",
            Self::HeatingSystem => "2450",
            Self::PublicUtilityUse => "2460",
            Self::PumpRoom => "2470",
            Self::EffluentTreatment => "2480",
            Self::TreatmentInstallation => "2490",
            Self::RecyclingInstallation => "2500",
            Self::Chancel => "2600",
            Self::Sacristy => "2610",
            Self::BellTower => "2620",
            Self::BaptismRoom => "2630",
            Self::Confessional => "2640",
            Self::Benches => "2650",
            Self::Pulpit => "2660",
            Self::Lobby => "2670",
            Self::Parish => "2680",
            Self::Chapel => "2690",
            Self::PoliceStation => "2700",
            Self::Headquarters => "2710",
            Self::PrisonCell => "2720",
            Self::MotorPoolHall => "2730",
            Self::FireBrigadeEmergencyVehicle => "2740",
            Self::RelaxationRoom2750 => "2750",
            Self::ToolPipeStore => "2760",
            Self::EmergencyCallCenter => "2770",
            Self::ArmsDepot => "2780",
            Self::AmmunitionDump => "2790",
            Self::VehicleHall => "2800",
            Self::PanicRoom => "2810",
            Self::SatelliteReceiver => "2900",
            Self::CommunicationRoom => "2910",
            Self::IndustrialBuilding => "3000",
            Self::ProductionBuilding => "3010",
            Self::FactoryBuilding => "3020",
            Self::Workshop => "3030",
            Self::StorageDepot => "3040",
            Self::ColdStorage => "3050",
            Self::Store => "3060",
            Self::StationConcourse => "3100",
            Self::Track => "3110",
            Self::TicketOffice3120 => "3120",
            Self::WaitingHall => "3130",
            Self::EngineShed => "3140",
            Self::SignalBox => "3150",
            Self::DepartureTerminal => "3160",
            Self::CheckOutCounter => "3170",
            Self::CheckInCounter => "3180",
            Self::Check => "3190",
            Self::BaggageCarousel => "3200",
            Self::SecurityCheck => "3210",
            Self::Classroom => "3300",
            Self::StaffRoom => "3310",
            Self::BreakOrRecessHall => "3320",
            Self::Laboratory => "3330",
            Self::UtilityRoom3340 => "3340",
            Self::MediaRoom3350 => "3350",
            Self::ScienceLaboratory => "3360",
            Self::SportsHall => "3370",
            Self::SchoolLibrary => "3380",
            Self::Office3390 => "3390",
            Self::LectureTheatre => "3400",
            Self::Refectory => "3410",
            Self::FunctionRoom => "3420",
            Self::Other(s) => s,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ecitygml_core::model::building::values::BuildingRoomFunctionValue;
    use egml::model::basic_types::Code;

    #[test]
    fn round_trips_known_codes() {
        for (code, value) in [
            ("1000", Sig3dBuildingRoomFunctionValue::LivingRoom),
            ("3420", Sig3dBuildingRoomFunctionValue::FunctionRoom),
        ] {
            assert_eq!(Sig3dBuildingRoomFunctionValue::from_code_value(code), value);
            assert_eq!(value.to_code_value(), code);
        }
    }

    #[test]
    fn unrecognized_code_in_this_code_space_falls_back_to_other() {
        let value = Sig3dBuildingRoomFunctionValue::from_code_value("999999");
        assert_eq!(
            value,
            Sig3dBuildingRoomFunctionValue::Other("999999".to_string())
        );
        assert_eq!(value.to_code_value(), "999999");
    }

    #[test]
    fn interprets_bare_code_with_no_code_space() {
        let wrapped = BuildingRoomFunctionValue::from(Code::new("1000"));
        assert_eq!(
            wrapped.interpret::<Sig3dBuildingRoomFunctionValue>(),
            Some(Sig3dBuildingRoomFunctionValue::LivingRoom)
        );
    }

    #[test]
    fn does_not_interpret_a_different_code_space() {
        let wrapped = BuildingRoomFunctionValue::from(Code::with_code_space(
            "https://example.org/local-codes",
            "1000",
        ));
        assert_eq!(wrapped.interpret::<Sig3dBuildingRoomFunctionValue>(), None);
    }
}
