use ecitygml_core::model::common::CodeListValue;

/// The SIG3D standard code list `BuildingFurniture_usage.xml` (version 2.0).
///
/// <https://www.sig3d.de/codelists/standard/building/2.0/BuildingFurniture_usage.xml>
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Sig3dBuildingFurnitureUsageValue {
    Cupboard,
    Wardrobe,
    Cabinet,
    Sideboard,
    Locker,
    ToolCabinet,
    Shelf,
    Rack,
    CoatStand,
    Table,
    DiningTable,
    CoffeeTable,
    Desk,
    BedsideCabinet,
    BabyChangingTable,
    Bar,
    PoolTable,
    SnookerTable,
    RouletteTable,
    WorkBench,
    Chair,
    Bench,
    OfficeChair,
    Sofa,
    RockingChair,
    BarStool,
    Armchair,
    Bed,
    Crib,
    BunkBed,
    Cradle,
    Cot,
    Stretcher,
    Lighting,
    StandardLamp,
    CeilingLight,
    Spotlight,
    ElectricAppliances,
    TelevisionSet,
    VideoRecorder,
    StereoUnit,
    KitchenAppliances,
    Cooker,
    Oven,
    Refrigerator,
    CoffeeMachine,
    Toaster,
    Kettle,
    Microwave,
    DishWasher,
    LaundryEquipment,
    WashingMachine,
    IroningMachine,
    RotaryIronMangle,
    LaundryTumbleDrier,
    SpinDrier,
    TechnicalOfficeEquipment,
    CopyMachine,
    Scanner,
    Plotter,
    Printer,
    Screen1950,
    Computer,
    OverheadProjector,
    VideoProjector,
    SanitationEquipment,
    SinkHandBasin,
    WaterTap,
    ToiletBowl,
    Bathtub,
    Shower,
    Bidet,
    AnimalPark,
    Aquarium,
    Cage,
    Birdcage,
    ReligiousEquipment,
    ShopFittings,
    SalesCounter,
    GlassCabinet,
    ChangingCubicle,
    RefrigeratedCounter,
    CashDeskOrTillOrCounter,
    BoxOffice,
    Machines,
    TicketMachine,
    CigaretteMachine,
    CashMachineOrAtm,
    VendingMachine,
    GamblingMachine,
    TechnicalFurniture,
    HeatingInstallation,
    Tank,
    OilTank,
    WaterTank,
    GasTank,
    FuelTank,
    MilkTank,
    SteelTank,
    FireProtectionAppliance,
    FireExtinguishingSystem,
    FireAlarm,
    FireExtinguisher,
    SwitchBoard,
    LiftingPlatform,
    CompressedAirSystem,
    LoudSpeaker,
    Microphone,
    SportsEquipment,
    GoalPosts,
    BasketballBasket,
    VolleyballNet,
    GymnasticApparatus,
    DivingPlatform,
    SwimmingPool,
    SalesPromotionFurniture,
    DisplayPanel,
    Billboard,
    DisplayCabinet,
    FunctionalFurniture,
    Ashtray,
    Lectern,
    Stage,
    Blackboard,
    Screen2825,
    Mapstand,
    RubbishBin,
    Sauna,
    Carpet,
    WallClock,
    Curtain,
    Mirror,
    /// A value within this code list's codeSpace that isn't one of the
    /// entries above.
    Other(String),
}

impl CodeListValue for Sig3dBuildingFurnitureUsageValue {
    const CODE_SPACE: &'static str =
        "http://www.sig3d.org/codelists/citygml/2.0/building/2.0/BuildingFurniture_usage.xml";

    fn from_code_value(value: &str) -> Self {
        match value {
            "1000" => Self::Cupboard,
            "1010" => Self::Wardrobe,
            "1020" => Self::Cabinet,
            "1030" => Self::Sideboard,
            "1040" => Self::Locker,
            "1050" => Self::ToolCabinet,
            "1100" => Self::Shelf,
            "1110" => Self::Rack,
            "1120" => Self::CoatStand,
            "1200" => Self::Table,
            "1210" => Self::DiningTable,
            "1220" => Self::CoffeeTable,
            "1230" => Self::Desk,
            "1240" => Self::BedsideCabinet,
            "1250" => Self::BabyChangingTable,
            "1260" => Self::Bar,
            "1270" => Self::PoolTable,
            "1280" => Self::SnookerTable,
            "1290" => Self::RouletteTable,
            "1270" => Self::WorkBench,
            "1300" => Self::Chair,
            "1310" => Self::Bench,
            "1320" => Self::OfficeChair,
            "1330" => Self::Sofa,
            "1340" => Self::RockingChair,
            "1350" => Self::BarStool,
            "1360" => Self::Armchair,
            "1400" => Self::Bed,
            "1410" => Self::Crib,
            "1420" => Self::BunkBed,
            "1430" => Self::Cradle,
            "1440" => Self::Cot,
            "1450" => Self::Stretcher,
            "1500" => Self::Lighting,
            "1510" => Self::StandardLamp,
            "1520" => Self::CeilingLight,
            "1530" => Self::Spotlight,
            "1600" => Self::ElectricAppliances,
            "1610" => Self::TelevisionSet,
            "1620" => Self::VideoRecorder,
            "1630" => Self::StereoUnit,
            "1700" => Self::KitchenAppliances,
            "1710" => Self::Cooker,
            "1720" => Self::Oven,
            "1730" => Self::Refrigerator,
            "1740" => Self::CoffeeMachine,
            "1750" => Self::Toaster,
            "1760" => Self::Kettle,
            "1770" => Self::Microwave,
            "1780" => Self::DishWasher,
            "1800" => Self::LaundryEquipment,
            "1810" => Self::WashingMachine,
            "1820" => Self::IroningMachine,
            "1830" => Self::RotaryIronMangle,
            "1840" => Self::LaundryTumbleDrier,
            "1850" => Self::SpinDrier,
            "1900" => Self::TechnicalOfficeEquipment,
            "1910" => Self::CopyMachine,
            "1920" => Self::Scanner,
            "1930" => Self::Plotter,
            "1940" => Self::Printer,
            "1950" => Self::Screen1950,
            "1960" => Self::Computer,
            "1970" => Self::OverheadProjector,
            "1980" => Self::VideoProjector,
            "2000" => Self::SanitationEquipment,
            "2010" => Self::SinkHandBasin,
            "2020" => Self::WaterTap,
            "2030" => Self::ToiletBowl,
            "2040" => Self::Bathtub,
            "2050" => Self::Shower,
            "2060" => Self::Bidet,
            "2100" => Self::AnimalPark,
            "2110" => Self::Aquarium,
            "2120" => Self::Cage,
            "2130" => Self::Birdcage,
            "2200" => Self::ReligiousEquipment,
            "2300" => Self::ShopFittings,
            "2310" => Self::SalesCounter,
            "2320" => Self::GlassCabinet,
            "2330" => Self::ChangingCubicle,
            "2340" => Self::RefrigeratedCounter,
            "2350" => Self::CashDeskOrTillOrCounter,
            "2360" => Self::BoxOffice,
            "2400" => Self::Machines,
            "2410" => Self::TicketMachine,
            "2420" => Self::CigaretteMachine,
            "2430" => Self::CashMachineOrAtm,
            "2440" => Self::VendingMachine,
            "2450" => Self::GamblingMachine,
            "2500" => Self::TechnicalFurniture,
            "2510" => Self::HeatingInstallation,
            "2520" => Self::Tank,
            "2521" => Self::OilTank,
            "2522" => Self::WaterTank,
            "2523" => Self::GasTank,
            "2524" => Self::FuelTank,
            "2525" => Self::MilkTank,
            "2526" => Self::SteelTank,
            "2530" => Self::FireProtectionAppliance,
            "2531" => Self::FireExtinguishingSystem,
            "2532" => Self::FireAlarm,
            "2533" => Self::FireExtinguisher,
            "2540" => Self::SwitchBoard,
            "2550" => Self::LiftingPlatform,
            "2560" => Self::CompressedAirSystem,
            "2570" => Self::LoudSpeaker,
            "2580" => Self::Microphone,
            "2600" => Self::SportsEquipment,
            "2610" => Self::GoalPosts,
            "2620" => Self::BasketballBasket,
            "2630" => Self::VolleyballNet,
            "2640" => Self::GymnasticApparatus,
            "2650" => Self::DivingPlatform,
            "2660" => Self::SwimmingPool,
            "2700" => Self::SalesPromotionFurniture,
            "2710" => Self::DisplayPanel,
            "2720" => Self::Billboard,
            "2730" => Self::DisplayCabinet,
            "2800" => Self::FunctionalFurniture,
            "2805" => Self::Ashtray,
            "2810" => Self::Lectern,
            "2815" => Self::Stage,
            "2820" => Self::Blackboard,
            "2825" => Self::Screen2825,
            "2830" => Self::Mapstand,
            "2835" => Self::RubbishBin,
            "2840" => Self::Sauna,
            "2845" => Self::Carpet,
            "2850" => Self::WallClock,
            "2855" => Self::Curtain,
            "2860" => Self::Mirror,
            other => Self::Other(other.to_string()),
        }
    }

    fn to_code_value(&self) -> &str {
        match self {
            Self::Cupboard => "1000",
            Self::Wardrobe => "1010",
            Self::Cabinet => "1020",
            Self::Sideboard => "1030",
            Self::Locker => "1040",
            Self::ToolCabinet => "1050",
            Self::Shelf => "1100",
            Self::Rack => "1110",
            Self::CoatStand => "1120",
            Self::Table => "1200",
            Self::DiningTable => "1210",
            Self::CoffeeTable => "1220",
            Self::Desk => "1230",
            Self::BedsideCabinet => "1240",
            Self::BabyChangingTable => "1250",
            Self::Bar => "1260",
            Self::PoolTable => "1270",
            Self::SnookerTable => "1280",
            Self::RouletteTable => "1290",
            Self::WorkBench => "1270",
            Self::Chair => "1300",
            Self::Bench => "1310",
            Self::OfficeChair => "1320",
            Self::Sofa => "1330",
            Self::RockingChair => "1340",
            Self::BarStool => "1350",
            Self::Armchair => "1360",
            Self::Bed => "1400",
            Self::Crib => "1410",
            Self::BunkBed => "1420",
            Self::Cradle => "1430",
            Self::Cot => "1440",
            Self::Stretcher => "1450",
            Self::Lighting => "1500",
            Self::StandardLamp => "1510",
            Self::CeilingLight => "1520",
            Self::Spotlight => "1530",
            Self::ElectricAppliances => "1600",
            Self::TelevisionSet => "1610",
            Self::VideoRecorder => "1620",
            Self::StereoUnit => "1630",
            Self::KitchenAppliances => "1700",
            Self::Cooker => "1710",
            Self::Oven => "1720",
            Self::Refrigerator => "1730",
            Self::CoffeeMachine => "1740",
            Self::Toaster => "1750",
            Self::Kettle => "1760",
            Self::Microwave => "1770",
            Self::DishWasher => "1780",
            Self::LaundryEquipment => "1800",
            Self::WashingMachine => "1810",
            Self::IroningMachine => "1820",
            Self::RotaryIronMangle => "1830",
            Self::LaundryTumbleDrier => "1840",
            Self::SpinDrier => "1850",
            Self::TechnicalOfficeEquipment => "1900",
            Self::CopyMachine => "1910",
            Self::Scanner => "1920",
            Self::Plotter => "1930",
            Self::Printer => "1940",
            Self::Screen1950 => "1950",
            Self::Computer => "1960",
            Self::OverheadProjector => "1970",
            Self::VideoProjector => "1980",
            Self::SanitationEquipment => "2000",
            Self::SinkHandBasin => "2010",
            Self::WaterTap => "2020",
            Self::ToiletBowl => "2030",
            Self::Bathtub => "2040",
            Self::Shower => "2050",
            Self::Bidet => "2060",
            Self::AnimalPark => "2100",
            Self::Aquarium => "2110",
            Self::Cage => "2120",
            Self::Birdcage => "2130",
            Self::ReligiousEquipment => "2200",
            Self::ShopFittings => "2300",
            Self::SalesCounter => "2310",
            Self::GlassCabinet => "2320",
            Self::ChangingCubicle => "2330",
            Self::RefrigeratedCounter => "2340",
            Self::CashDeskOrTillOrCounter => "2350",
            Self::BoxOffice => "2360",
            Self::Machines => "2400",
            Self::TicketMachine => "2410",
            Self::CigaretteMachine => "2420",
            Self::CashMachineOrAtm => "2430",
            Self::VendingMachine => "2440",
            Self::GamblingMachine => "2450",
            Self::TechnicalFurniture => "2500",
            Self::HeatingInstallation => "2510",
            Self::Tank => "2520",
            Self::OilTank => "2521",
            Self::WaterTank => "2522",
            Self::GasTank => "2523",
            Self::FuelTank => "2524",
            Self::MilkTank => "2525",
            Self::SteelTank => "2526",
            Self::FireProtectionAppliance => "2530",
            Self::FireExtinguishingSystem => "2531",
            Self::FireAlarm => "2532",
            Self::FireExtinguisher => "2533",
            Self::SwitchBoard => "2540",
            Self::LiftingPlatform => "2550",
            Self::CompressedAirSystem => "2560",
            Self::LoudSpeaker => "2570",
            Self::Microphone => "2580",
            Self::SportsEquipment => "2600",
            Self::GoalPosts => "2610",
            Self::BasketballBasket => "2620",
            Self::VolleyballNet => "2630",
            Self::GymnasticApparatus => "2640",
            Self::DivingPlatform => "2650",
            Self::SwimmingPool => "2660",
            Self::SalesPromotionFurniture => "2700",
            Self::DisplayPanel => "2710",
            Self::Billboard => "2720",
            Self::DisplayCabinet => "2730",
            Self::FunctionalFurniture => "2800",
            Self::Ashtray => "2805",
            Self::Lectern => "2810",
            Self::Stage => "2815",
            Self::Blackboard => "2820",
            Self::Screen2825 => "2825",
            Self::Mapstand => "2830",
            Self::RubbishBin => "2835",
            Self::Sauna => "2840",
            Self::Carpet => "2845",
            Self::WallClock => "2850",
            Self::Curtain => "2855",
            Self::Mirror => "2860",
            Self::Other(s) => s,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trips_known_codes() {
        for (code, value) in [
            ("1000", Sig3dBuildingFurnitureUsageValue::Cupboard),
            ("2860", Sig3dBuildingFurnitureUsageValue::Mirror),
        ] {
            assert_eq!(
                Sig3dBuildingFurnitureUsageValue::from_code_value(code),
                value
            );
            assert_eq!(value.to_code_value(), code);
        }
    }

    #[test]
    fn unrecognized_code_in_this_code_space_falls_back_to_other() {
        let value = Sig3dBuildingFurnitureUsageValue::from_code_value("999999");
        assert_eq!(
            value,
            Sig3dBuildingFurnitureUsageValue::Other("999999".to_string())
        );
        assert_eq!(value.to_code_value(), "999999");
    }
}
