use strum_macros::{Display, EnumIter};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, EnumIter, Display)]
pub enum FeatureType {
    AuxiliaryTrafficArea,
    AuxiliaryTrafficSpace,
    Bridge,
    BridgeConstructiveElement,
    BridgeFurniture,
    BridgeInstallation,
    BridgePart,
    BridgeRoom,
    Building,
    BuildingConstructiveElement,
    BuildingFurniture,
    BuildingInstallation,
    BuildingPart,
    BuildingRoom,
    BuildingUnit,
    CeilingSurface,
    CityFurniture,
    CityObjectGroup,
    ClearanceSpace,
    ClosureSurface,
    Door,
    DoorSurface,
    FloorSurface,
    GenericLogicalSpace,
    GenericOccupiedSpace,
    GenericThematicSurface,
    GenericUnoccupiedSpace,
    GroundSurface,
    Hole,
    HoleSurface,
    HollowSpace,
    InteriorWallSurface,
    Intersection,
    Marking,
    OtherConstruction,
    OuterCeilingSurface,
    OuterFloorSurface,
    PlantCover,
    Railway,
    ReliefFeature,
    Road,
    RoofSurface,
    Section,
    SolitaryVegetationObject,
    Square,
    Storey,
    TinRelief,
    Track,
    TrafficArea,
    TrafficSpace,
    Tunnel,
    TunnelConstructiveElement,
    TunnelFurniture,
    TunnelInstallation,
    TunnelPart,
    WallSurface,
    WaterBody,
    WaterGroundSurface,
    WaterSurface,
    Waterway,
    Window,
    WindowSurface,
}

impl FeatureType {
    pub fn is_top_level(&self) -> bool {
        match self {
            FeatureType::AuxiliaryTrafficArea => false,
            FeatureType::AuxiliaryTrafficSpace => false,
            FeatureType::Bridge => true,
            FeatureType::BridgeConstructiveElement => false,
            FeatureType::BridgeFurniture => false,
            FeatureType::BridgeInstallation => false,
            FeatureType::BridgePart => false,
            FeatureType::BridgeRoom => false,
            FeatureType::Building => true,
            FeatureType::BuildingConstructiveElement => false,
            FeatureType::BuildingFurniture => false,
            FeatureType::BuildingInstallation => false,
            FeatureType::BuildingPart => false,
            FeatureType::BuildingRoom => false,
            FeatureType::BuildingUnit => false,
            FeatureType::CeilingSurface => false,
            FeatureType::CityFurniture => true,
            FeatureType::CityObjectGroup => true,
            FeatureType::ClearanceSpace => false,
            FeatureType::ClosureSurface => false,
            FeatureType::Door => false,
            FeatureType::DoorSurface => false,
            FeatureType::FloorSurface => false,
            FeatureType::GenericLogicalSpace => true,
            FeatureType::GenericOccupiedSpace => true,
            FeatureType::GenericThematicSurface => false,
            FeatureType::GenericUnoccupiedSpace => true,
            FeatureType::GroundSurface => false,
            FeatureType::Hole => false,
            FeatureType::HoleSurface => false,
            FeatureType::HollowSpace => false,
            FeatureType::InteriorWallSurface => false,
            FeatureType::Intersection => false,
            FeatureType::Marking => false,
            FeatureType::OtherConstruction => true,
            FeatureType::OuterCeilingSurface => false,
            FeatureType::OuterFloorSurface => false,
            FeatureType::PlantCover => true,
            FeatureType::Railway => true,
            FeatureType::ReliefFeature => true,
            FeatureType::Road => true,
            FeatureType::RoofSurface => false,
            FeatureType::Section => false,
            FeatureType::SolitaryVegetationObject => true,
            FeatureType::Square => false,
            FeatureType::Storey => false,
            FeatureType::TinRelief => false,
            FeatureType::Track => true,
            FeatureType::TrafficArea => false,
            FeatureType::TrafficSpace => false,
            FeatureType::Tunnel => true,
            FeatureType::TunnelConstructiveElement => false,
            FeatureType::TunnelFurniture => false,
            FeatureType::TunnelInstallation => false,
            FeatureType::TunnelPart => false,
            FeatureType::WallSurface => false,
            FeatureType::WaterBody => true,
            FeatureType::WaterGroundSurface => false,
            FeatureType::WaterSurface => false,
            FeatureType::Waterway => true,
            FeatureType::Window => false,
            FeatureType::WindowSurface => false,
        }
    }
}
