use strum::{Display, EnumIter};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, EnumIter, Display)]
pub enum XmlElement {
    Appearance,
    AppearanceMemberProperty,
    AppearanceProperty,
    AuxiliaryTrafficArea,
    AuxiliaryTrafficSpace,
    AuxiliaryTrafficSpaceProperty,
    BoundaryProperty,
    Building,
    BuildingConstructiveElement,
    BuildingConstructiveElementProperty,
    BuildingInstallation,
    BuildingInstallationProperty,
    BuildingPart,
    BuildingPartProperty,
    BuildingRoom,
    BuildingRoomProperty,
    BuildingSubdivisionProperty,
    BuildingUnit,
    CeilingSurface,
    CityFurniture,
    CityModel,
    CityObjectMemberProperty,
    ClearanceSpace,
    ClearanceSpaceProperty,
    ClosureSurface,
    Door,
    DoorSurface,
    FillingElementProperty,
    FillingSurfaceProperty,
    FloorSurface,
    GenericAttributeProperty,
    GenericOccupiedSpace,
    GenericThematicSurface,
    GeoreferencedTexture,
    GroundSurface,
    InteriorWallSurface,
    Intersection,
    IntersectionProperty,
    LandUse,
    Marking,
    MarkingProperty,
    OuterCeilingSurface,
    OuterFloorSurface,
    ParameterizedTexture,
    PlantCover,
    PointCloud,
    PointCloudProperty,
    ReliefComponentProperty,
    ReliefFeature,
    Road,
    RoofSurface,
    Section,
    SectionProperty,
    SolitaryVegetationObject,
    Storey,
    SurfaceDataProperty,
    TINRelief,
    TrafficArea,
    TrafficSpace,
    TrafficSpaceProperty,
    WallSurface,
    WaterBody,
    WaterGroundSurface,
    WaterSurface,
    Window,
    WindowSurface,
    X3DMaterial,
}

impl XmlElement {
    pub fn as_str(&self) -> &str {
        match self {
            XmlElement::Appearance => "app:Appearance",
            XmlElement::AppearanceMemberProperty => "appearanceMember",
            XmlElement::AppearanceProperty => "app:appearance",
            XmlElement::AuxiliaryTrafficArea => "tran:AuxiliaryTrafficArea",
            XmlElement::AuxiliaryTrafficSpace => "tran:AuxiliaryTrafficSpace",
            XmlElement::AuxiliaryTrafficSpaceProperty => "tran:auxiliaryTrafficSpace",
            XmlElement::BoundaryProperty => "boundary",
            XmlElement::Building => "bldg:Building",
            XmlElement::BuildingConstructiveElement => "bldg:BuildingConstructiveElement",
            XmlElement::BuildingConstructiveElementProperty => "bldg:buildingConstructiveElement",
            XmlElement::BuildingInstallation => "bldg:BuildingInstallation",
            XmlElement::BuildingInstallationProperty => "bldg:buildingInstallation",
            XmlElement::BuildingPart => "bldg:BuildingPart",
            XmlElement::BuildingPartProperty => "bldg:buildingPart",
            XmlElement::BuildingRoom => "bldg:BuildingRoom",
            XmlElement::BuildingRoomProperty => "bldg:buildingRoom",
            XmlElement::BuildingSubdivisionProperty => "bldg:buildingSubdivision",
            XmlElement::BuildingUnit => "bldg:BuildingUnit",
            XmlElement::CeilingSurface => "con:CeilingSurface",
            XmlElement::CityFurniture => "frn:CityFurniture",
            XmlElement::CityModel => "CityModel",
            XmlElement::CityObjectMemberProperty => "cityObjectMember",
            XmlElement::ClearanceSpace => "tran:ClearanceSpace",
            XmlElement::ClearanceSpaceProperty => "tran:clearanceSpace",
            XmlElement::ClosureSurface => "ClosureSurface",
            XmlElement::Door => "con:Door",
            XmlElement::DoorSurface => "con:DoorSurface",
            XmlElement::FillingElementProperty => "filling",
            XmlElement::FillingSurfaceProperty => "fillingSurface",
            XmlElement::FloorSurface => "con:FloorSurface",
            XmlElement::GenericAttributeProperty => "genericAttribute",
            XmlElement::GenericOccupiedSpace => "gen:GenericOccupiedSpace",
            XmlElement::GenericThematicSurface => "gen:GenericThematicSurface",
            XmlElement::GeoreferencedTexture => "app:GeoreferencedTexture",
            XmlElement::GroundSurface => "con:GroundSurface",
            XmlElement::InteriorWallSurface => "con:InteriorWallSurface",
            XmlElement::Intersection => "tran:Intersection",
            XmlElement::IntersectionProperty => "tran:intersection",
            XmlElement::LandUse => "luse:LandUse",
            XmlElement::Marking => "tran:Marking",
            XmlElement::MarkingProperty => "tran:marking",
            XmlElement::OuterCeilingSurface => "con:OuterCeilingSurface",
            XmlElement::OuterFloorSurface => "con:OuterFloorSurface",
            XmlElement::ParameterizedTexture => "app:ParameterizedTexture",
            XmlElement::PlantCover => "veg:PlantCover",
            XmlElement::PointCloud => "pcl:PointCloud",
            XmlElement::PointCloudProperty => "pointCloud",
            XmlElement::ReliefComponentProperty => "dem:reliefComponent",
            XmlElement::ReliefFeature => "dem:ReliefFeature",
            XmlElement::Road => "tran:Road",
            XmlElement::RoofSurface => "con:RoofSurface",
            XmlElement::Section => "tran:Section",
            XmlElement::SectionProperty => "tran:section",
            XmlElement::SolitaryVegetationObject => "veg:SolitaryVegetationObject",
            XmlElement::Storey => "bldg:Storey",
            XmlElement::SurfaceDataProperty => "app:surfaceData",
            XmlElement::TINRelief => "dem:TINRelief",
            XmlElement::TrafficArea => "tran:TrafficArea",
            XmlElement::TrafficSpace => "tran:TrafficSpace",
            XmlElement::TrafficSpaceProperty => "tran:trafficSpace",
            XmlElement::WallSurface => "con:WallSurface",
            XmlElement::WaterBody => "wtr:WaterBody",
            XmlElement::WaterGroundSurface => "wtr:WaterGroundSurface",
            XmlElement::WaterSurface => "wtr:WaterSurface",
            XmlElement::Window => "con:Window",
            XmlElement::WindowSurface => "con:WindowSurface",
            XmlElement::X3DMaterial => "app:X3DMaterial",
        }
    }

    pub fn from_local_name(local_name: &[u8]) -> Option<Self> {
        match local_name {
            b"Appearance" => Some(Self::Appearance),
            b"AuxiliaryTrafficArea" => Some(Self::AuxiliaryTrafficArea),
            b"AuxiliaryTrafficSpace" => Some(Self::AuxiliaryTrafficSpace),
            b"Building" => Some(Self::Building),
            b"BuildingConstructiveElement" => Some(Self::BuildingConstructiveElement),
            b"BuildingInstallation" => Some(Self::BuildingInstallation),
            b"BuildingPart" => Some(Self::BuildingPart),
            b"BuildingRoom" => Some(Self::BuildingRoom),
            b"BuildingUnit" => Some(Self::BuildingUnit),
            b"CeilingSurface" => Some(Self::CeilingSurface),
            b"CityFurniture" => Some(Self::CityFurniture),
            b"ClearanceSpace" => Some(Self::ClearanceSpace),
            b"ClosureSurface" => Some(Self::ClosureSurface),
            b"Door" => Some(Self::Door),
            b"DoorSurface" => Some(Self::DoorSurface),
            b"FloorSurface" => Some(Self::FloorSurface),
            b"GenericOccupiedSpace" => Some(Self::GenericOccupiedSpace),
            b"GenericThematicSurface" => Some(Self::GenericThematicSurface),
            b"GeoreferencedTexture" => Some(Self::GeoreferencedTexture),
            b"GroundSurface" => Some(Self::GroundSurface),
            b"InteriorWallSurface" => Some(Self::InteriorWallSurface),
            b"Intersection" => Some(Self::Intersection),
            b"LandUse" => Some(Self::LandUse),
            b"Marking" => Some(Self::Marking),
            b"OuterCeilingSurface" => Some(Self::OuterCeilingSurface),
            b"OuterFloorSurface" => Some(Self::OuterFloorSurface),
            b"ParameterizedTexture" => Some(Self::ParameterizedTexture),
            b"PlantCover" => Some(Self::PlantCover),
            b"PointCloud" => Some(Self::PointCloud),
            b"ReliefFeature" => Some(Self::ReliefFeature),
            b"Road" => Some(Self::Road),
            b"RoofSurface" => Some(Self::RoofSurface),
            b"Section" => Some(Self::Section),
            b"SolitaryVegetationObject" => Some(Self::SolitaryVegetationObject),
            b"Storey" => Some(Self::Storey),
            b"TINRelief" => Some(Self::TINRelief),
            b"TrafficArea" => Some(Self::TrafficArea),
            b"TrafficSpace" => Some(Self::TrafficSpace),
            b"WallSurface" => Some(Self::WallSurface),
            b"WaterBody" => Some(Self::WaterBody),
            b"WaterGroundSurface" => Some(Self::WaterGroundSurface),
            b"WaterSurface" => Some(Self::WaterSurface),
            b"Window" => Some(Self::Window),
            b"WindowSurface" => Some(Self::WindowSurface),
            b"X3DMaterial" => Some(Self::X3DMaterial),
            b"appearance" => Some(Self::AppearanceProperty),
            b"appearanceMember" => Some(Self::AppearanceMemberProperty),
            b"auxiliaryTrafficSpace" => Some(Self::AuxiliaryTrafficSpaceProperty),
            b"boundary" => Some(Self::BoundaryProperty),
            b"buildingConstructiveElement" => Some(Self::BuildingConstructiveElementProperty),
            b"buildingInstallation" => Some(Self::BuildingInstallationProperty),
            b"buildingPart" => Some(Self::BuildingPartProperty),
            b"buildingRoom" => Some(Self::BuildingRoomProperty),
            b"buildingSubdivision" => Some(Self::BuildingSubdivisionProperty),
            b"cityObjectMember" => Some(Self::CityObjectMemberProperty),
            b"clearanceSpace" => Some(Self::ClearanceSpaceProperty),
            b"filling" => Some(Self::FillingElementProperty),
            b"fillingSurface" => Some(Self::FillingSurfaceProperty),
            b"genericAttribute" => Some(Self::GenericAttributeProperty),
            b"intersection" => Some(Self::IntersectionProperty),
            b"marking" => Some(Self::MarkingProperty),
            b"pointCloud" => Some(Self::PointCloudProperty),
            b"reliefComponent" => Some(Self::ReliefComponentProperty),
            b"section" => Some(Self::SectionProperty),
            b"surfaceData" => Some(Self::SurfaceDataProperty),
            b"trafficSpace" => Some(Self::TrafficSpaceProperty),
            _ => {
                tracing::debug!(
                    "unknown XML element: {}",
                    String::from_utf8_lossy(local_name)
                );
                None
            }
        }
    }
}
